"""Generate every Course map view and every Note's "Where this fits" box from concepts.yaml.

Usage: python course_map/build_map.py
Writes:
  01-course-map/note.md and its images (Pipeline map, Concept maps, Algorithm chooser)
  <note>/images/where_this_fits.tex and the "Where this fits" block of every written Note
The interactive version is course_map/app.py (it reads the same file)."""
import re
import shutil
import subprocess
from pathlib import Path

import plotly.graph_objects as go
import yaml

ROOT = Path(__file__).resolve().parent.parent
DATA = yaml.safe_load(open(ROOT / "course_map" / "concepts.yaml"))
STEPS = DATA["steps"]
NOTES = DATA["notes"]
CONCEPTS = {c["id"]: c for c in DATA["concepts"]}
LINKS = [dict(zip(("a", "type", "b", "status"), link)) for link in DATA["links"]]
LINK_TYPES = ("needs", "is a kind of", "fixes", "compared with", "used in")
SHORT = {0: "Foundations", 1: "Frame", 2: "Get data", 3: "Understand", 4: "Clean", 5: "Features", 6: "Reduce",
         7: "Split", 8: "Model", 9: "Evaluate", 10: "Tune", 11: "Deploy", 12: "Test", 13: "Monitor"}
STEP_COLOUR = {0: "#6B6B6B", 1: "#B279A2", 2: "#4C78A8", 3: "#4C78A8", 4: "#4C78A8", 5: "#54A24B", 6: "#54A24B",
               7: "#54A24B", 8: "#F58518", 9: "#E45756", 10: "#E45756", 11: "#72B7B2", 12: "#72B7B2", 13: "#72B7B2"}
LINK_COLOUR = {"needs": "#4C78A8", "is a kind of": "#6B6B6B", "fixes": "#54A24B", "compared with": "#B279A2",
               "used in": "#F58518"}
BEGIN = "<!-- where-this-fits: generated by course_map/build_map.py; edit concepts.yaml, not this block -->"
END = "<!-- /where-this-fits -->"
# Concept map areas: the Model step is split in two so each picture stays readable.
TREES_AND_GROUPS = {"decision_tree", "regression_tree", "ensemble", "voting", "bagging", "random_forest", "boosting",
                    "adaboost", "gradient_boosting", "xgboost", "stacking", "clustering", "anomaly_detection",
                    "association_rules", "kmeans", "hierarchical", "dbscan"}
AREAS = [("foundations", "Foundations and framing", lambda c: c["step"] <= 1),
         ("data", "Getting, understanding and cleaning data", lambda c: 2 <= c["step"] <= 4),
         ("features", "Features, dimensions and splitting", lambda c: 5 <= c["step"] <= 7),
         ("models_1", "Models: regression, classification and gradient descent",
          lambda c: c["step"] == 8 and c["id"] not in TREES_AND_GROUPS),
         ("models_2", "Models: trees, ensembles and clustering",
          lambda c: c["step"] == 8 and c["id"] in TREES_AND_GROUPS),
         ("production", "Evaluating, tuning and production", lambda c: c["step"] >= 9)]


def validate():
    errors = []
    for link in LINKS:
        for end in (link["a"], link["b"]):
            if end not in CONCEPTS:
                errors.append(f"unknown concept {end!r} in link {link}")
        if link["type"] not in LINK_TYPES:
            errors.append(f"unknown link type in {link}")
        if link["status"] not in ("draft", "confirmed"):
            errors.append(f"bad status in {link}")
    for c in CONCEPTS.values():
        extra = set(c) - {"id", "name", "step", "videos", "status"}
        if extra:
            errors.append(f"unexpected keys {extra} in {c['id']} (a name with a comma must be quoted)")
        if c["step"] not in STEPS:
            errors.append(f"bad step for {c['id']}")
        if c["status"] not in ("draft", "confirmed"):
            errors.append(f"bad status for {c['id']}")
    if errors:
        raise SystemExit("concepts.yaml has errors:\n" + "\n".join(errors))


def note_ref(video, md_dir):
    """'Note 7' with a link if written, else 'Video 7 (coming)'."""
    if video in NOTES:
        return f"[Note {video}]({md_dir}{NOTES[video]}/note.md)"
    return f"Note {video}, coming"


# ---------------------------------------------------------------- Where this fits

def neighbours(video):
    """Concepts this Video builds on, leads to and is compared with, each with the Video that teaches it."""
    own = {cid for cid, c in CONCEPTS.items() if video in c["videos"]}
    before, after, compare = {}, {}, {}

    def first_video(cid, earlier):
        vids = [v for v in CONCEPTS[cid]["videos"] if (v < video if earlier else v > video)]
        return (max(vids) if earlier else min(vids)) if vids else None

    for link in LINKS:
        a, t, b = link["a"], link["type"], link["b"]
        for mine, other, mine_is_a in ((a, b, True), (b, a, False)):
            if mine not in own or other in own:
                continue
            if t == "compared with":
                v = first_video(other, True) or first_video(other, False)
                if v:
                    compare[other] = v
                continue
            # needs / is a kind of: a builds on b.  fixes: b (the problem) comes first.  used in: a comes first.
            other_first = (t in ("needs", "is a kind of", "fixes")) == mine_is_a
            v = first_video(other, other_first)
            if v:
                (before if other_first else after)[other] = v
    return own, before, after, compare


def pipeline_strip(steps_here):
    """TikZ: the 14 Pipeline map steps in two rows, with this Note's steps highlighted."""
    cells = []
    for s, name in SHORT.items():
        x, y = (s % 7) * 2.15, -(s // 7) * 0.85
        on = s in steps_here
        colour = STEP_COLOUR[s].lstrip("#")
        style = (f"draw=c{s}, fill=c{s}!30, line width=1.6pt, font=\\scriptsize\\bfseries" if on
                 else "draw=cgrey!50, fill=white, text=cgrey!80, font=\\scriptsize")
        cells.append(f"  \\definecolor{{c{s}}}{{HTML}}{{{colour}}}\n"
                     f"  \\node[rounded corners=3pt, minimum width=2.0cm, minimum height=0.62cm, {style}] "
                     f"at ({x:.2f},{y:.2f}) {{{s} {name}}};")
    return ("\\documentclass[tikz,border=4pt]{standalone}\n\\input{../../tools/tikz-style.tex}\n"
            "\\begin{document}\n\\begin{tikzpicture}\n" + "\n".join(cells) + "\n\\end{tikzpicture}\n\\end{document}\n")


def concept_list(items, md_dir, limit=6):
    ranked = sorted(items.items(), key=lambda kv: (CONCEPTS[kv[0]]["status"] != "confirmed", kv[1]))[:limit]
    return "; ".join(f"{CONCEPTS[cid]['name']} ({note_ref(v, md_dir)})" for cid, v in ranked)


def where_block(video):
    own, before, after, compare = neighbours(video)
    steps_here = sorted({CONCEPTS[c]["step"] for c in own})
    lines = [BEGIN,
             "> **Where this fits:** Pipeline map " + ("step " if len(steps_here) == 1 else "steps ")
             + ", ".join(f"{s} ({STEPS[s]})" for s in steps_here) + ". See the [Course map](../01-course-map/note.md).",
             ">", "> ![](images/where_this_fits.png)", ">"]
    for label, items in (("Builds on", before), ("Leads to", after), ("Compare with", compare)):
        if items:
            lines.append(f"> - **{label}:** {concept_list(items, '../')}.")
    lines.append(END)
    return "\n".join(lines), steps_here


def update_note(video):
    folder = ROOT / NOTES[video]
    note = folder / "note.md"
    text = note.read_text()
    block, steps_here = where_block(video)
    (folder / "images").mkdir(exist_ok=True)
    (folder / "images" / "where_this_fits.tex").write_text(pipeline_strip(steps_here))
    text = re.sub(r"\n\*\*Prerequisites:\*\*[^\n]*\n", "\n", text)                    # replaced by the box
    if BEGIN in text:
        text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block, text, flags=re.S)
    else:
        first = text.index("\n## ")
        text = text[:first] + "\n" + block + "\n" + text[first:]
    note.write_text(text)


# ---------------------------------------------------------------- Course map Note (Video 1)

def pipeline_overview():
    """TikZ: the 14 steps as a snake with counts, and a loop between Understand and Clean."""
    nodes, arrows = [], []
    for s, name in STEPS.items():
        row, col = divmod(s, 5)
        x = (col if row % 2 == 0 else 4 - col) * 3.6
        y = -row * 2.3
        here = [c for c in CONCEPTS.values() if c["step"] == s]
        done = sum(c["status"] == "confirmed" for c in here)
        colour = STEP_COLOUR[s].lstrip("#")
        nodes.append(f"  \\definecolor{{c{s}}}{{HTML}}{{{colour}}}\n"
                     f"  \\node[box=c{s}, minimum width=3.0cm, minimum height=1.35cm] (s{s}) at ({x:.1f},{y:.1f}) "
                     f"{{\\textbf{{{s}. {name}}}\\\\{{\\small {done} of {len(here)} confirmed}}}};")
        if s:
            arrows.append(f"  \\draw[arrow] (s{s - 1}) -- (s{s});")
    loop = "  \\draw[arrow, draw=cred, dashed] (s4.north) to[bend right=35] node[above, font=\\scriptsize, text=cred] {back and forth} (s3.north);"
    return ("\\documentclass[tikz,border=8pt]{standalone}\n\\input{../../tools/tikz-style.tex}\n"
            "\\begin{document}\n\\begin{tikzpicture}\n" + "\n".join(nodes + arrows) + "\n" + loop
            + "\n\\end{tikzpicture}\n\\end{document}\n")


def graphviz_positions(nodes, edges, label):
    """Positions from Graphviz neato (layout only; Plotly draws). Boxes are sized to their labels so they never overlap."""
    dot = ["graph G {", 'graph [overlap=prism, sep="+4", splines=false];', "node [shape=box];"]
    for n in nodes:
        dot.append(f'"{n}" [width={len(label(n)) * 10.5 / 72 + 0.3:.2f}, height=0.42];')   # 18 px font, 72 px/inch
    for a, b in {tuple(sorted((e["a"], e["b"]))) for e in edges}:
        dot.append(f'"{a}" -- "{b}";')
    dot.append("}")
    out = subprocess.run(["neato", "-Tplain"], input="\n".join(dot), capture_output=True, text=True, check=True).stdout
    pos = {}
    for line in out.splitlines():
        parts = line.split()
        if parts and parts[0] == "node":
            pos[parts[1].strip('"')] = (float(parts[2]), float(parts[3]))
    return pos


def concept_map_figure(area_id, title, member):
    """Plotly: one area of the Concept map. Each Concept is a box coloured by pipeline step; Concepts from other
    areas that link in are grey. Drafts are faint, with dotted Links."""
    inside = {cid for cid, c in CONCEPTS.items() if member(c)}
    edges = [l for l in LINKS if l["a"] in inside or l["b"] in inside]
    nodes = sorted(inside | {e["a"] for e in edges} | {e["b"] for e in edges})
    pos = graphviz_positions(nodes, edges, lambda n: CONCEPTS[n]["name"])
    xs_all, ys_all = [p[0] for p in pos.values()], [p[1] for p in pos.values()]
    fig = go.Figure()
    for t in LINK_TYPES:
        for status, dash in (("confirmed", "solid"), ("draft", "dot")):
            xs, ys = [], []
            for e in edges:
                if e["type"] == t and e["status"] == status:
                    (x0, y0), (x1, y1) = pos[e["a"]], pos[e["b"]]
                    xs += [x0, x1, None]
                    ys += [y0, y1, None]
            if xs:
                fig.add_trace(go.Scatter(x=xs, y=ys, mode="lines", hoverinfo="skip",
                                         line=dict(color=LINK_COLOUR[t], width=2.6 if status == "confirmed" else 1.6, dash=dash),
                                         name=t + ("" if status == "confirmed" else " (draft)")))
    for e in edges:                                       # arrow heads half-way along: direction a -> b
        if e["type"] == "compared with":
            continue
        (x0, y0), (x1, y1) = pos[e["a"]], pos[e["b"]]
        fig.add_annotation(x=x0 + 0.58 * (x1 - x0), y=y0 + 0.58 * (y1 - y0), ax=x0 + 0.42 * (x1 - x0),
                           ay=y0 + 0.42 * (y1 - y0), xref="x", yref="y", axref="x", ayref="y", showarrow=True,
                           arrowhead=2, arrowsize=1.2, arrowwidth=1.6, arrowcolor=LINK_COLOUR[e["type"]], text="")
    for n in nodes:                                       # each Concept: a labelled box
        c = CONCEPTS[n]
        own = n in inside
        colour = STEP_COLOUR[c["step"]] if own else "#9A9A9A"
        fig.add_annotation(x=pos[n][0], y=pos[n][1], text=c["name"], showarrow=False,
                           font=dict(size=18 if own else 14, color="black" if own else "#6B6B6B"),
                           bgcolor=colour + ("40" if c["status"] == "confirmed" else "14"),
                           bordercolor=colour, borderwidth=2.4 if c["status"] == "confirmed" else 1, borderpad=4)
    pad, ppi = 1.6, 72                                    # Graphviz works in inches; 72 px/inch matches the box sizes
    width = int((max(xs_all) - min(xs_all) + 2 * pad) * ppi)
    height = int((max(ys_all) - min(ys_all) + 2 * pad) * ppi) + 140
    fig.update_layout(template="simple_white", width=max(width, 900), height=max(height, 600),
                      font=dict(family="Latin Modern Roman", size=15),
                      title=dict(text=f"Concept map: {title}", x=0.5),
                      xaxis=dict(visible=False, range=[min(xs_all) - pad, max(xs_all) + pad]),
                      yaxis=dict(visible=False, range=[min(ys_all) - pad, max(ys_all) + pad]),
                      legend=dict(orientation="h", x=0.5, xanchor="center", y=-0.02, title_text="Links: "),
                      margin=dict(l=10, r=10, t=60, b=70))
    out = ROOT / "01-course-map" / "images"
    fig.write_image(out / f"concept_map_{area_id}.png", scale=2)
    fig.write_image(out / f"concept_map_{area_id}.pdf")


def learning_path_rows():
    """One row per Video that has its own Concepts: what to read first."""
    rows = []
    videos = sorted({v for c in CONCEPTS.values() for v in c["videos"]})
    for v in videos:
        own, before, _, _ = neighbours(v)
        if not own:
            continue
        names = ", ".join(sorted(CONCEPTS[c]["name"] for c in own))
        first = sorted(set(before.values()))
        reads = ", ".join(note_ref(x, "../") for x in first[-4:]) or "nothing"
        status = "written" if v in NOTES else "coming"
        rows.append(f"| {v} | {names} | {reads} | {status} |")
    return rows


def course_map_note():
    out = ROOT / "01-course-map" / "images"
    out.mkdir(parents=True, exist_ok=True)
    (out / "pipeline_overview.tex").write_text(pipeline_overview())
    shutil.copy(ROOT / "course_map" / "algorithm_chooser.tex", out / "algorithm_chooser.tex")
    for area_id, title, member in AREAS:
        concept_map_figure(area_id, title, member)
    total = len(CONCEPTS)
    done = sum(c["status"] == "confirmed" for c in CONCEPTS.values())

    step_sections = []
    for s, name in STEPS.items():
        here = sorted((c for c in CONCEPTS.values() if c["step"] == s), key=lambda c: min(c["videos"]))
        rows = "\n".join(f"| {c['name']} | {', '.join(note_ref(v, '../') for v in c['videos'])} | {c['status']} |"
                         for c in here)
        step_sections.append(f"### 2.{s + 1} Step {s}: {name}\n\n| Concept | Taught in | Status |\n|---|---|---|\n{rows}\n")

    area_figs = "\n\n".join(f"![Concept map: {title}](images/concept_map_{area_id}.png){{height=88%}}" for area_id, title, _ in AREAS)
    text = f"""---
title: "Course Map"
---

## 1. Overview

> **Key point:** The Course map ties every Note together. It shows where each idea sits in an ML project, how ideas connect, what to read first, and which algorithm to choose.

The Notes each teach one lesson. The Course map shows how those lessons fit together, in four views:

| View | Question it answers |
|---|---|
| **Pipeline map** | Where does this idea sit in a real ML project? |
| **Concept map** | How is this idea connected to the others? |
| **Learning path** | Which Notes should I read first? |
| **Algorithm chooser** | Which algorithm suits my problem? |

Each idea on the map is a **Concept**. Concepts already taught in a written Note are **confirmed**; the others are **draft**, shown faint, and are checked against their source when their Note is written. So far, {done} of {total} Concepts are confirmed.

Every Note starts with a *Where this fits* box: a small Pipeline map with that Note's steps highlighted, plus what it builds on and what it leads to.

> **Extra:** This map is generated from one data file, `course_map/concepts.yaml`. An interactive version, where you can zoom, filter by step and click a Concept to see its links and Notes, runs with `python course_map/app.py`.

## 2. The Pipeline map

> **Key point:** Every ML project moves through the same steps, from framing the problem to monitoring the deployed model. Every Concept belongs to one step.

![The Pipeline map: 14 steps of an ML project](images/pipeline_overview.png)

Figure 1 shows the 14 steps. They follow the ML development life cycle: frame the problem, get and understand the data, clean it, engineer features, train and evaluate models, tune them, deploy, test and keep the model healthy.

Steps 3 (Understand data) and 4 (Clean) loop: exploring reveals what needs cleaning, and cleaning changes the data, so we explore again.

{chr(10).join(step_sections)}
## 3. The Concept map

> **Key point:** Concepts are joined by five kinds of Link. Following the Links shows why each idea exists and what it is for.

Every Link has one of five types:

| Link | Meaning | Example |
|---|---|---|
| **needs** | must be understood first | logistic regression *needs* gradient descent |
| **is a kind of** | a special case | Ridge *is a kind of* regularisation |
| **fixes** | solves a problem | regularisation *fixes* overfitting |
| **compared with** | often confused or contrasted | bagging *compared with* boosting |
| **used in** | a tool used inside something else | feature scaling *used in* KNN |

The full map has {total} Concepts, too many for one page, so it is shown in six areas (Figures 2 to 7). In each figure, the area's own Concepts are large and coloured by pipeline step; Concepts from other areas that link in are small and grey. Faint dots and dotted lines are drafts.

{area_figs}

## 4. The Learning path

> **Key point:** Before each Note, read the Notes it builds on.

Each row lists a Note's Concepts and the Notes to read first. Notes marked *coming* or *deferred* are not written yet.

| No. | Concepts | Read first | Note |
|---|---|---|---|
{chr(10).join(learning_path_rows())}

## 5. The Algorithm chooser

> **Key point:** Two questions narrow the choice: do we have labelled outputs, and are they numbers or categories?

![The Algorithm chooser (draft)](images/algorithm_chooser.png)

Figure 8 is a starting point, not a rule: in practice we try several suitable algorithms and compare them on a test set. It is a draft until the algorithm Notes are written.

## 6. Key terms

| Term | Meaning |
|---|---|
| Course map | The overview that ties all Notes together, in four views |
| Pipeline map | Where each Concept sits among the 14 steps of an ML project |
| Concept map | How Concepts are connected by Links |
| Learning path | Which Notes to read before which |
| Algorithm chooser | A flowchart from a problem's properties to suitable algorithms |
| Concept | One idea on the Course map |
| Link | A labelled connection between two Concepts |
| Draft / confirmed | Guessed from titles / checked against a written Note |
"""
    (ROOT / "01-course-map" / "note.md").write_text(text)


if __name__ == "__main__":
    validate()
    course_map_note()
    for video in NOTES:
        update_note(video)
    print(f"Course map built: {len(CONCEPTS)} concepts, {len(LINKS)} links, {len(NOTES)} Notes updated.")
