"""Generate every Course map view and every Note's "Where this fits" box from concepts.yaml.

Usage: python course_map/build_map.py
Writes:
  00-course-map/00-course-map.md and its images (Pipeline map, Concept maps, Algorithm chooser)
  <note>/images/where_this_fits.tex and the "Where this fits" block of every written Note
The interactive version is course_map/app.py (it reads the same file)."""
import re
import shutil
from pathlib import Path

import plotly.graph_objects as go
import yaml

ROOT = Path(__file__).resolve().parent.parent
import sys
sys.path.insert(0, str(ROOT / "tools"))
from section_links import slug as anchor  # noqa: E402  (GitHub-style heading anchor; build_map has its own slug for tags)
DATA = yaml.safe_load(open(ROOT / "course_map" / "concepts.yaml"))
STEPS = DATA["steps"]
NOTES = DATA["notes"]


def subject(video):
    """'MA', 'ML' or 'DL': the Subject prefix of the Note's folder."""
    return NOTES[video].split("/")[0]


def chapter(video):
    return NOTES[video].split("/")[1]


def label(video):
    """'ML-049': the Note number shown in text."""
    return Path(NOTES[video]).name[:6]


def note_file(video):
    return ROOT / NOTES[video] / f"{Path(NOTES[video]).name}.md"
CONCEPTS = {c["id"]: c for c in DATA["concepts"]}
LINKS = [dict(zip(("a", "type", "b", "status"), link)) for link in DATA["links"]]
LINK_TYPES = ("needs", "is a kind of", "fixes", "compared with", "used in")
SHORT = {0: "Foundations", 1: "Frame", 2: "Get data", 3: "Understand", 4: "Clean", 5: "Features", 6: "Reduce",
         7: "Split", 8: "Model", 9: "Evaluate", 10: "Tune", 11: "Deploy", 12: "Test", 13: "Monitor"}
STEP_COLOUR = {0: "#6B6B6B", 1: "#B279A2", 2: "#4C78A8", 3: "#4C78A8", 4: "#4C78A8", 5: "#54A24B", 6: "#54A24B",
               7: "#54A24B", 8: "#F58518", 9: "#E45756", 10: "#E45756", 11: "#72B7B2", 12: "#72B7B2", 13: "#72B7B2"}
LINK_COLOUR = {"needs": "#B279A2", "is a kind of": "#6B6B6B", "fixes": "#54A24B", "compared with": "#4C78A8",
               "used in": "#F58518"}
BEGIN = "<!-- where-this-fits: generated by course_map/build_map.py; edit concepts.yaml, not this block -->"
END = "<!-- /where-this-fits -->"
# Concept map areas: the Model step is split in two so each picture stays readable.
TREES_AND_GROUPS = {"decision_tree", "regression_tree", "ensemble", "voting", "bagging", "random_forest", "boosting",
                    "adaboost", "gradient_boosting", "xgboost", "stacking", "clustering", "anomaly_detection",
                    "association_rules", "kmeans", "hierarchical", "dbscan"}
def first_note(c):
    """The Note that teaches the Concept. A maths or statistics Concept (step 0) may first appear in an ML Note
    that uses it; its home is the maths or statistics Note (Subject MA)."""
    if not c["videos"]:
        return 0
    maths = [v for v in c["videos"] if subject(v) == "MA"]
    return min(maths) if c["step"] == 0 and maths else min(c["videos"])


def ml(c):  # ML playlist Concepts; maths, statistics and deep learning get their own areas
    return subject(first_note(c)) == "ML"


# Maths Chapters by Concept map topic (a topic can span several Chapters).
MATHS_TOPICS = {"linear_algebra": ("00-why-maths", "05-linear-algebra"),
                "descriptive": ("01-descriptive-stats", "03-distributions"),
                "probability": ("02-probability",),
                "inference": ("04-inference",),
                "calculus": ("06-calculus", "07-optimisation"),
                "likelihood": ("08-likelihood",)}


def maths_topic(c):
    v = first_note(c)
    return next((t for t, chapters in MATHS_TOPICS.items() if subject(v) == "MA" and chapter(v) in chapters), None)


def dl_chapter(c):
    v = first_note(c)
    return chapter(v) if subject(v) == "DL" else None


AREAS = [("foundations", "Foundations and framing", lambda c: ml(c) and c["step"] <= 1),
         ("data", "Getting, understanding and cleaning data", lambda c: ml(c) and 2 <= c["step"] <= 4),
         ("features", "Features, dimensions and splitting", lambda c: ml(c) and 5 <= c["step"] <= 7),
         ("models_1", "Models: regression, classification and gradient descent",
          lambda c: ml(c) and c["step"] == 8 and c["id"] not in TREES_AND_GROUPS),
         ("models_2", "Models: trees, ensembles and clustering",
          lambda c: ml(c) and c["step"] == 8 and c["id"] in TREES_AND_GROUPS),
         ("production", "Evaluating, tuning and production", lambda c: ml(c) and c["step"] >= 9),
         ("descriptive", "Descriptive statistics and distributions", lambda c: maths_topic(c) == "descriptive"),
         ("probability", "Probability", lambda c: maths_topic(c) == "probability"),
         ("inference", "Sampling, inference and hypothesis tests", lambda c: maths_topic(c) == "inference"),
         ("linear_algebra", "Linear algebra", lambda c: maths_topic(c) == "linear_algebra"),
         ("calculus", "Calculus and optimisation", lambda c: maths_topic(c) == "calculus"),
         ("likelihood", "Likelihood, MLE and mixture models", lambda c: maths_topic(c) == "likelihood"),
         ("dl_basics", "Deep learning: perceptron to backpropagation", lambda c: dl_chapter(c) in ("01-basics",)),
         ("dl_training", "Deep learning: training better networks", lambda c: dl_chapter(c) in ("02-training",)),
         ("dl_optimizers", "Deep learning: optimizers", lambda c: dl_chapter(c) in ("03-optimizers",)),
         ("dl_cnn", "Deep learning: convolutional networks", lambda c: dl_chapter(c) in ("04-cnn",)),
         ("dl_rnn", "Deep learning: recurrent networks", lambda c: dl_chapter(c) in ("05-rnn",)),
         ("dl_transformers", "Deep learning: LLMs, attention and transformers", lambda c: dl_chapter(c) in ("06-transformers",))]


def validate():
    errors = []
    for link in LINKS:
        for end in (link["a"], link["b"]):
            if end not in CONCEPTS:
                errors.append(f"unknown concept {end!r} in link {link}")
        if link["type"] not in LINK_TYPES:
            errors.append(f"unknown link type in {link}")
        if link["status"] not in ("draft", "confirmed"):
            errors.append(f"bad status in {link}")
    for c in CONCEPTS.values():
        extra = set(c) - {"id", "name", "step", "videos", "status"}
        if extra:
            errors.append(f"unexpected keys {extra} in {c['id']} (a name with a comma must be quoted)")
        if c["step"] not in STEPS:
            errors.append(f"bad step for {c['id']}")
        if c["status"] not in ("draft", "confirmed"):
            errors.append(f"bad status for {c['id']}")
    if errors:
        raise SystemExit("concepts.yaml has errors:\n" + "\n".join(errors))


def note_ref(video, md_dir):
    """A link 'Note ML-007' if written, else the bare video number, marked coming."""
    if video in NOTES:
        return f"[Note {label(video)}]({md_dir}{NOTES[video]}/{Path(NOTES[video]).name}.md)"
    return f"Note {video}, coming"


# ---------------------------------------------------------------- Where this fits

def neighbours(video):
    """Concepts this Video builds on, leads to and is compared with, each with the Video that teaches it."""
    own = {cid for cid, c in CONCEPTS.items() if video in c["videos"]}
    before, after, compare = {}, {}, {}

    def first_video(cid, earlier):
        vids = [v for v in CONCEPTS[cid]["videos"] if (v < video if earlier else v > video)]
        return (max(vids) if earlier else min(vids)) if vids else None

    for link in LINKS:
        a, t, b = link["a"], link["type"], link["b"]
        for mine, other, mine_is_a in ((a, b, True), (b, a, False)):
            if mine not in own or other in own:
                continue
            if t == "compared with":
                v = first_video(other, True) or first_video(other, False)
                if v:
                    compare[other] = v
                continue
            # needs / is a kind of: a builds on b.  fixes: b (the problem) comes first.  used in: a comes first.
            other_first = (t in ("needs", "is a kind of", "fixes")) == mine_is_a
            # "Builds on" points at the Note that teaches the concept (its owner), not merely the nearest
            # earlier Note that uses it; "Leads to" points at the next Note that uses it
            v = first_note(CONCEPTS[other]) if other_first else first_video(other, False)
            if v and v != video:
                (before if other_first else after)[other] = v
    return own, before, after, compare


def pipeline_strip(steps_here):
    """TikZ: the 14 Pipeline map steps in two rows, with this Note's steps highlighted."""
    cells = []
    for s, name in SHORT.items():
        x, y = (s % 7) * 2.15, -(s // 7) * 0.85
        on = s in steps_here
        colour = STEP_COLOUR[s].lstrip("#")
        style = (f"draw=c{s}, fill=c{s}!30, line width=1.6pt, font=\\scriptsize\\bfseries" if on
                 else "draw=cgrey!50, fill=white, text=cgrey!80, font=\\scriptsize")
        cells.append(f"  \\definecolor{{c{s}}}{{HTML}}{{{colour}}}\n"
                     f"  \\node[rounded corners=3pt, minimum width=2.0cm, minimum height=0.62cm, {style}] "
                     f"at ({x:.2f},{y:.2f}) {{{s} {name}}};")
    return ("\\documentclass[tikz,border=4pt]{standalone}\n\\input{../../../../tools/tikz-style.tex}\n"
            "\\begin{document}\n\\begin{tikzpicture}\n" + "\n".join(cells) + "\n\\end{tikzpicture}\n\\end{document}\n")


def section_of(note_md, name):
    """Anchor of the section that teaches `name` in a Note: the heading above its first bold mention, else above its
    first plain mention, else "" (NOTE-RULES §17). Headings with maths are skipped (unreliable anchors)."""
    if not note_md.exists():
        return ""
    lines = note_md.read_text(encoding="utf-8").splitlines()
    lines = lines[next((i for i, l in enumerate(lines) if l.startswith("<!-- /where-this-fits")), 0):]
    base = re.sub(r"\s*\([^)]*\)", "", name).strip()                 # "Deep (stacked) RNNs" -> "Deep RNNs"
    keys = [name, base] + re.findall(r"\(([^)]*)\)", name) + re.split(r",| and ", base)
    keys = [k.strip().lower() for k in keys if len(k.strip()) > 3]
    keys += [k[:-1] for k in keys if k.endswith("s")]                  # "bidirectional rnns" -> "...rnn"
    for line in lines:                                  # the earliest heading that names it wins (it teaches it)
        m = re.match(r"^#{2,6}\s+(.*?)\s*$", line)
        h = m.group(1).lower() if m else ""
        if h and "$" not in h and any(k in h for k in keys) \
                and not re.match(r"[\d.]+ (overview|summary|sources|key terms)", h):
            return "#" + anchor(m.group(1))
    first = ""
    for bold in (True, False):                     # a bold (defining) mention of any name form beats a plain one
        for key in keys:
            heading = ""
            for line in lines:
                m = re.match(r"^#{2,6}\s+(.*?)\s*$", line)
                if m:
                    heading = m.group(1) if "$" not in m.group(1) else heading
                    first = first or heading
                    continue
                low = line.lower()
                if heading and ((f"**{key}**" in low) if bold else key in low) and not line.startswith("!["):
                    return "#" + anchor(heading)
    return "#" + anchor(first) if first else ""      # the whole Note is about it: its Overview


def concept_link(cid, video, md_dir):
    """[Concept name](Note.md#section that teaches it): the idea is the link text, not "Note XX-NNN" (§17)."""
    name = CONCEPTS[cid]["name"]
    if video not in NOTES:
        return f"{name} (coming)"
    rel = f"{NOTES[video]}/{Path(NOTES[video]).name}.md"
    return f"[{name}]({md_dir}{rel}{section_of(ROOT / rel, name)})"


def concept_list(items, md_dir, limit=6):
    ranked = sorted(items.items(), key=lambda kv: (CONCEPTS[kv[0]]["status"] != "confirmed", kv[1]))[:limit]
    return "; ".join(concept_link(cid, v, md_dir) for cid, v in ranked)


def where_block(video):
    own, before, after, compare = neighbours(video)
    steps_here = sorted({CONCEPTS[c]["step"] for c in own})
    lines = [BEGIN,
             "> **Where this fits:** Pipeline map " + ("step " if len(steps_here) == 1 else "steps ")
             + ", ".join(f"{s} ({STEPS[s]})" for s in steps_here) + ". See the [Course map](../../../00-course-map/00-course-map.md).",
             ">", "> ![](images/where_this_fits.png)", ">"]
    for label, items in (("Builds on", before), ("Leads to", after), ("Compare with", compare)):
        if items:
            lines.append(f"> - **{label}:** {concept_list(items, '../../../')}.")
    lines.append(END)
    return "\n".join(lines), steps_here


def slug(text):
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def note_tags(video):
    """Obsidian tags for a Note: its areas, pipeline steps and the Concepts it teaches, all from concepts.yaml."""
    here = [c for c in CONCEPTS.values() if video in c["videos"]]
    areas = sorted({a for a, _, member in AREAS for c in here if member(c)})
    steps = sorted({c["step"] for c in here})
    subj = {"DL": "deep-learning", "ML": "ml"}.get(subject(video)) or (
        "statistics" if maths_topic({"videos": [video], "step": 0}) in ("descriptive", "probability", "inference")
        else "maths")
    return ([f"subject/{subj}"] + [f"area/{slug(a)}" for a in areas] + [f"step/{slug(SHORT[s])}" for s in steps]
            + sorted(f"concept/{slug(c['id'])}" for c in here))


def set_tags(text, video):
    """Write the tags line into the front matter, replacing an old one; the PDF build ignores it."""
    tags = note_tags(video)
    text = re.sub(r"\ntags: \[[^\]]*\]", "", text, count=1)
    if tags and text.startswith("---\n"):
        end = text.index("\n---", 4)
        text = text[:end] + f"\ntags: [{', '.join(tags)}]" + text[end:]
    return text


def update_note(video):
    folder = ROOT / NOTES[video]
    note = note_file(video)
    text = set_tags(note.read_text(), video)
    block, steps_here = where_block(video)
    (folder / "images").mkdir(exist_ok=True)
    (folder / "images" / "where_this_fits.tex").write_text(pipeline_strip(steps_here))
    text = re.sub(r"\n\*\*Prerequisites:\*\*[^\n]*\n", "\n", text)                    # replaced by the box
    if BEGIN in text:
        text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), lambda _: block, text, flags=re.S)
    else:
        first = text.index("\n## ")
        text = text[:first] + "\n" + block + "\n" + text[first:]
    note.write_text(text)


# ---------------------------------------------------------------- Course map Note (Video 1)

def pipeline_overview():
    """TikZ: the 14 steps as a snake with counts, and a loop between Understand and Clean."""
    nodes, arrows = [], []
    for s, name in STEPS.items():
        row, col = divmod(s, 5)
        x = (col if row % 2 == 0 else 4 - col) * 3.6
        y = -row * 2.3
        here = [c for c in CONCEPTS.values() if c["step"] == s]
        done = sum(c["status"] == "confirmed" for c in here)
        colour = STEP_COLOUR[s].lstrip("#")
        nodes.append(f"  \\definecolor{{c{s}}}{{HTML}}{{{colour}}}\n"
                     f"  \\node[box=c{s}, minimum width=3.0cm, minimum height=1.35cm] (s{s}) at ({x:.1f},{y:.1f}) "
                     f"{{\\textbf{{{s}. {name}}}\\\\{{\\small {done} of {len(here)} confirmed}}}};")
        if s:
            arrows.append(f"  \\draw[arrow] (s{s - 1}) -- (s{s});")
    loop = "  \\draw[arrow, draw=cred, dashed] (s4.north) to[bend right=35] node[above, font=\\scriptsize, text=cred] {back and forth} (s3.north);"
    return ("\\documentclass[tikz,border=8pt]{standalone}\n\\input{../../tools/tikz-style.tex}\n"
            "\\begin{document}\n\\begin{tikzpicture}\n" + "\n".join(nodes + arrows) + "\n" + loop
            + "\n\\end{tikzpicture}\n\\end{document}\n")


def note_title(video):
    """The Note's own title from its front matter; 'Note N, coming' for Notes not written yet."""
    if video not in NOTES:
        return f"Note {video}, coming"
    m = re.search(r'^title:\s*"(.*)"', note_file(video).read_text(), re.M)
    return f"{label(video)} " + (m.group(1) if m else Path(NOTES[video]).name)


# Hand-designed TikZ mind maps (course_map/mindmaps/<id>.tex), in reading order. Auto-laid-out graphs of the
# whole map were unreadable; the interactive app (app.py) shows every link instead.
MINDMAPS = [("foundations", "Foundations and framing"), ("data", "Getting, understanding and cleaning data"),
            ("features", "Features, dimensions and splitting"),
            ("models_regression", "Models: regression, classification and gradient descent"),
            ("models_trees", "Models: trees, ensembles and clustering"),
            ("production", "Evaluating, tuning and production"),
            ("descriptive", "Descriptive statistics and distributions"), ("probability", "Probability"),
            ("inference", "Sampling, inference and hypothesis tests"), ("linear_algebra", "Linear algebra"),
            ("calculus", "Calculus and optimisation"), ("likelihood", "Likelihood, MLE and mixture models"),
            ("dl_basics", "Deep learning: perceptron to backpropagation"),
            ("dl_training", "Deep learning: training better networks"), ("dl_optimizers", "Deep learning: optimizers"),
            ("dl_cnn", "Deep learning: convolutional networks"), ("dl_rnn", "Deep learning: recurrent networks"),
            ("dl_transformers", "Deep learning: LLMs, attention and transformers")]


def learning_path_rows():
    """One row per Video that has its own Concepts: what to read first."""
    rows = []
    videos = sorted({v for c in CONCEPTS.values() for v in c["videos"]})
    for v in videos:
        own, before, _, _ = neighbours(v)
        if not own:
            continue
        names = ", ".join(sorted(CONCEPTS[c]["name"] for c in own))
        first = sorted(set(before.values()))
        reads = ", ".join(note_ref(x, "../") for x in first[-4:]) or "nothing"
        status = "written" if v in NOTES else "coming"
        rows.append(f"| {label(v) if v in NOTES else v} | {names} | {reads} | {status} |")
    return rows



def reading_rounds(target=1004):
    """The rounds of the reading-order figure (same rule as 00-course-map/images/learning_path.py)."""
    def read_first(v):
        _, before, _, _ = neighbours(v)
        return sorted(set(before.values()))[-4:]
    r1 = read_first(target)
    seen = {target, *r1}
    r2 = []
    for x in r1:
        feeds = [y for y in read_first(x) if y not in seen]
        seen.update(feeds)
        r2.append((x, feeds))
    r1_text = ", ".join(f"Note {label(v)}" for v in r1[:-1]) + f" and Note {label(r1[-1])}"
    parts = []
    for x, feeds in r2:
        parts.append(f"Note {label(x)} builds on " + (", ".join(f"Note {label(y)}" for y in feeds) if feeds else "nothing new"))
    return r1_text, "; ".join(parts)

def course_map_note():
    r1_text, r2_text = reading_rounds()
    out = ROOT / "00-course-map" / "images"
    out.mkdir(parents=True, exist_ok=True)
    (out / "pipeline_overview.tex").write_text(pipeline_overview())
    shutil.copy(ROOT / "course_map" / "algorithm_chooser.tex", out / "algorithm_chooser.tex")
    maps = [(m, t) for m, t in MINDMAPS if (ROOT / "course_map" / "mindmaps" / f"{m}.pdf").exists()]
    for old in out.glob("concept_map_*"):
        old.unlink()
    for m, _ in maps:
        for ext in ("pdf", "png"):
            shutil.copy(ROOT / "course_map" / "mindmaps" / f"{m}.{ext}", out / f"concept_map_{m}.{ext}")
    total = len(CONCEPTS)
    done = sum(c["status"] == "confirmed" for c in CONCEPTS.values())

    step_sections = []
    for s, name in STEPS.items():
        here = sorted((c for c in CONCEPTS.values() if c["step"] == s), key=lambda c: min(c["videos"]))
        rows = "\n".join(f"| {c['name']} | {', '.join(note_ref(v, '../') for v in c['videos'])} | {c['status']} |"
                         for c in here)
        step_sections.append(f"### 2.{s + 1} Step {s}: {name}\n\n| Concept | Taught in | Status |\n|---|---|---|\n{rows}\n")

    area_figs = "\n\n".join(f"![Concept map: {title}](images/concept_map_{m}.png){{width=100%}}" for m, title in maps)
    text = f"""---
title: "Course Map"
---

## 1. Overview

> **Key point:** The Course map ties every Note together. It shows where each idea sits in an ML project, how ideas connect, what to read first, and which algorithm to choose.

The Notes each teach one lesson. The **Course map** (G-2160) shows how those lessons fit together, in four views:

| View | Question it answers |
|---|---|
| **Pipeline map** (G-2161) | Where does this idea sit in a real ML project? |
| **Concept map** (G-2162) | How is this idea connected to the others? |
| **Learning path** (G-2163) | Which Notes should I read first? |
| **Algorithm chooser** (G-2164) | Which algorithm suits my problem? |

Each idea on the map is a **Concept** (G-2165). Concepts already taught in a written Note are **confirmed**; the others are **draft** (G-2167), shown faint, and are checked against their source when their Note is written. So far, {done} of {total} Concepts are confirmed.

Every Note starts with a *Where this fits* box: a small Pipeline map with that Note's steps highlighted, plus what it builds on and what it leads to.

> **Extra:** This map is generated from one data file, `course_map/concepts.yaml`. An interactive version, where you can zoom, filter by step and click a Concept to see its links and Notes, runs with `python course_map/app.py`.

<!-- playground: images/concept_playground.html -->

## 2. The Pipeline map

> **Key point:** Every ML project moves through the same steps, from framing the problem to monitoring the deployed model. Every Concept belongs to one step.

![The Pipeline map: 14 steps of an ML project](images/pipeline_overview.png)

Figure 1 shows the 14 steps. They follow the ML development life cycle, or **MLDLC** (G-1240):

1. frame the problem;
2. get the data and understand it;
3. clean the data;
4. engineer features;
5. train and evaluate models;
6. tune them;
7. deploy, test and keep the model healthy.

Steps 3 (Understand data) and 4 (Clean) loop: exploring reveals what needs cleaning, and cleaning changes the data, so we explore again.

{chr(10).join(step_sections)}
## 3. The Concept map

> **Key point:** Concepts are joined by five kinds of Link. Following the Links shows why each idea exists and what it is for.

Every **Link** (G-2166) has one of five types:

| Link | Meaning | Example |
|---|---|---|
| **needs** | must be understood first | logistic regression *needs* gradient descent |
| **is a kind of** | a special case | Ridge *is a kind of* regularisation |
| **fixes** | solves a problem | regularisation *fixes* overfitting |
| **compared with** | often confused or contrasted | bagging *compared with* boosting |
| **used in** | a tool used inside something else | feature scaling *used in* KNN |

The full map has {total} Concepts, too many for one page, so each topic has its own mind map (Figures 2 to {len(maps) + 1}). Each map tells the topic's story from left to right and shows only its key Concepts and links; the grey number in each box is the Note that teaches it, and dashed boxes lead to other maps. To see every Concept and every link at once, open `course_map/concept_map_3d.html` in a browser: a 3D network you can rotate and zoom, with one colour per area (rebuilt by `python course_map/map_3d.py`). The interactive app (`python course_map/app.py`) lists each Concept's links with the Notes that teach them.

{area_figs}

## 4. The Learning path

> **Key point:** Before each Note, read the Notes it builds on.

A Note is easiest to read when the ideas it uses are already familiar. The Notes that teach those ideas are its **prerequisites**: the Notes to read first. Each prerequisite has prerequisites of its own, so the reading order grows backwards from the Note we want, one round at a time.

![The reading order for the perceptron Note (DL-004), grown backwards. Round 1 adds the three Notes it builds on; round 2 adds the Notes that those build on. Arrows point from a prerequisite to the Note that needs it.](images/learning_path.gif)

Figure {len(maps) + 2} builds the reading order for the perceptron Note (Note DL-004) step by step:

1. **Goal.** We want to read Note DL-004.
2. **Round 1.** Its row in the table below lists {r1_text}.
3. **Round 2.** Each of those has its own row: {r2_text}.
4. **Reading.** Read the picture from left to right: green Notes first, then blue, then the goal. Every arrow points from a Note to a Note that needs it.

Each row of the table lists a Note's Concepts and the Notes to read first, with at most the four most recent. A row comes from the **needs**, **is a kind of**, **fixes** and **used in** Links of section 3: when a Concept of the Note builds on another Concept, the latest earlier Note that teaches that other Concept is read first. Notes marked *coming* or *deferred* are not written yet.

| No. | Concepts | Read first | Note |
|---|---|---|---|
{chr(10).join(learning_path_rows())}

## 5. The Algorithm chooser

> **Key point:** Two questions narrow the choice: do we have labelled outputs, and are they numbers or categories?

![The Algorithm chooser (draft)](images/algorithm_chooser.png)

Figure {len(maps) + 3} is a starting point, not a rule: in practice we try several suitable algorithms and compare them on a test set. It is a draft until the algorithm Notes are written.

## 6. Sources

**Built from**
- CampusX, "100 Days of Machine Learning", YouTube playlist (134 videos), https://www.youtube.com/playlist?list=PLKnIA16_Rmvbr7zKYQuBfsVkjoLcJgxHH
- CampusX, "100 Days of Deep Learning", YouTube playlist (84 videos), https://www.youtube.com/playlist?list=PLKnIA16_RmvYuZauWaPlRTC54KxSNLtNn
- CampusX, "Maths for Machine Learning", YouTube playlist (23 sessions), https://www.youtube.com/playlist?list=PLKnIA16_RmvbYFaaeLY28cWeqV-3vADST
- Every Note listed in the Learning path: each Note's own Sources name the video, book or paper it was built from.

**Other references**
- The Concept map data: `course_map/concepts.yaml` in this repository.

## 7. Key terms

| Term | Meaning |
|---|---|
| Course map (G-2160) | The overview that ties all Notes together, in four views |
| Pipeline map (G-2161) | Where each Concept sits among the 14 steps of an ML project |
| Concept map (G-2162) | How Concepts are connected by Links |
| Learning path (G-2163) | Which Notes to read before which |
| Algorithm chooser (G-2164) | A flowchart from a problem's properties to suitable algorithms |
| Concept (G-2165) | One idea on the Course map |
| Link (G-2166) | A labelled connection between two Concepts |
| Draft / confirmed (G-2167) | Guessed from titles / checked against a written Note |
"""
    (ROOT / "00-course-map" / "00-course-map.md").write_text(text)


if __name__ == "__main__":
    validate()
    course_map_note()
    for video in NOTES:
        update_note(video)
    print(f"Course map built: {len(CONCEPTS)} concepts, {len(LINKS)} links, {len(NOTES)} Notes updated.")
