# Hand judgements per Note: (core process idea or '', animated, [proposals], gold source)
# animated: Y = core process animated, P = an animation exists but misses the core process, N = process not animated, - = no process
# proposal: "what | tool | data | effort"
A = {
'map': ('', '-', [], ''),
'01': ('', '-', [], ''),
'02': ('', '-', [], '3b1b NN Ch1 (layers of a digit net) - already echoed by layers_digit.gif'),
'03': ('RL agent-environment loop', 'Y', [], ''),
'04': ('', '-', [], ''),
'05': ('model updating after each mini-batch', 'Y', [], ''),
'06': ('KNN predicting by neighbours', 'Y', [], ''),
'07': ('', '-', [], ''),
'08': ('', '-', [], ''),
'09': ('nine-stage cycle', 'Y', ['Replace 4 text-only stage sections with one TikZ stage strip that highlights the current stage at the top of each section | TikZ | stage names from mldlc_cycle | simple'], ''),
'11': ('', '-', [], ''),
'12': ('', '-', ['One TikZ "where code runs" diagram per tool (local conda env, Jupyter kernel, Colab VM) so each of the 9 sections has a picture | TikZ | the Note\'s own setup steps | simple'], ''),
'13': ('', '-', [], ''),
'14': ('', '-', ['TikZ decision flow: business goal -> ML task -> metric -> online/batch, with the Note\'s Netflix/churn example filled into each box | TikZ | Note example | simple'], ''),
'15': ('reading a CSV in chunks', 'Y', ['Annotated CSV-to-DataFrame panel per read_csv parameter group (sep, usecols, dtype, na_values), so the 18 sections are not text-only | TikZ | the Note\'s sample CSV | simple'], ''),
'16': ('', '-', [], ''),
'17': ('paging through an API', 'Y', [], ''),
'18': ('loop over HTML containers', 'Y', [], ''),
'19': ('', '-', [], ''),
'20': ('', '-', [], ''),
'21': ('', '-', [], ''),
'22': ('', '-', [], ''),
'23': ('', '-', ['One before/after table picture per FE family (transform, construct, select, extract) on Titanic rows | TikZ | Titanic | simple'], ''),
'24': ('subtract mean, divide by std', 'Y', [], 'StatQuest "Standard deviation vs standard error" (spread intuition)'),
'25': ('min-max squeeze to [0,1]', 'Y', [], ''),
'26': ('', '-', ['TikZ mapping arrows category -> integer for ordinal vs label encoder, with the wrong-order trap shown as crossing arrows | TikZ | Note columns | simple'], ''),
'27': ('', '-', [], ''),
'28': ('columns routed to transformers', 'Y', [], ''),
'29': ('data flowing through pipeline steps', 'Y', ['Show fit vs transform: Plotly-frame GIF where train rows flow through and learn (mean, scaler) while test rows only flow through using stored values | Plotly frames | Titanic pipeline from the Note | medium'], ''),
'30': ('', '-', [], ''),
'31': ('lambda reshaping a skewed column', 'Y', [], ''),
'32': ('k-means bin edges settling', 'Y', [], ''),
'33': ('', '-', ['TikZ split diagram: one mixed cell "C23" -> letter column + number column | TikZ | Titanic Cabin/Ticket | simple'], ''),
'34': ('', '-', ['Timeline strip showing a timestamp broken into year/month/weekday/hour features | TikZ | Note dataset | simple'], ''),
'35': ('', '-', [], ''),
'36': ('', '-', [], ''),
'37': ('', '-', ['Bar-chart before/after mode fill vs "Missing" category on the Note\'s house-price column, side by side | Plotly | Note data | simple'], ''),
'38': ('random sample imputation draws', 'N', ['Animate random-sample imputation: each NaN Age gets a value drawn from the observed Age histogram; histogram shape stays the same while mean fill makes a spike | Plotly frames | Titanic Age | simple'], ''),
'39': ('KNN distance fill', 'Y', [], ''),
'40': ('MICE rounds converging', 'Y', [], ''),
'41': ('', '-', ['TikZ panel: trim vs cap drawn on one number line per section | TikZ | Note numbers | simple'], ''),
'42': ('', '-', [], ''),
'43': ('', '-', ['Box plot building its fences from Q1/Q3 then flagging points (reuse 230 boxplot_build approach) | Plotly frames | placement CGPA data | simple'], ''),
'44': ('', '-', [], ''),
'45': ('', '-', [], ''),
'46': ('points spreading apart as dimensions grow', 'Y', [], ''),
'47': ('rotating axes to max variance', 'Y', [], 'StatQuest "PCA main ideas"; 3b1b Essence LA Ch13 change of basis'),
'48': ('covariance matrix stretching vectors; projection', 'Y', [], 'StatQuest "PCA step-by-step"; 3b1b Essence LA Ch14'),
'49': ('', '-', [], ''),
'50': ('line search to best fit', 'Y', [], 'StatQuest "Linear Regression, clearly explained"'),
'51': ('least squares: moving m,b changes squared residuals', 'N', ['Two linked panels: line with residual squares on the CGPA-package data (left) and the dot on the (m,b) loss surface (right), sweeping m then b to the OLS optimum | Plotly frames | placement CGPA vs package | medium'], 'StatQuest "Linear Regression" (residual squares)'),
'52': ('R2 as fraction of variance explained', 'N', ['Animate residual squares shrinking as the fit goes from mean line to regression line; R2 bar fills | Plotly frames | CGPA-package | simple'], 'StatQuest "R-squared, clearly explained"'),
'53': ('fitting a plane to 2 features', 'N', ['Rotating 3D plane fit with residual sticks | Plotly frames (camera orbit) | Note data (CGPA, IQ -> package) | simple'], ''),
'54': ('normal equation as projection', 'N', ['Manim: y projected onto the column space of X; residual drops perpendicular, giving X^T(y - Xb)=0 | Manim | 3-row toy X from the Note | medium'], '3b1b Essence LA Ch9 (dot products/projection), Ch8 (non-square matrices)'),
'55': ('', '-', ['Predicted-vs-actual scatter and coefficient bar chart for the diabetes fit | Plotly | sklearn diabetes | simple'], ''),
'56': ('', '-', [], ''),
'57': ('gradient descent steps', 'Y', ['Upgrade: 2-param (m,b) descent on a contour map synced with the line fitting the data | Plotly frames | CGPA-package | medium'], '3b1b NN Ch2 "Gradient descent, how neural networks learn"; StatQuest "Gradient Descent, Step-by-Step"'),
'58': ('batch GD full-data steps', 'N', ['Batch GD path on the diabetes loss contours, one frame per epoch, with loss curve beside it | Plotly frames | sklearn diabetes | simple'], 'StatQuest "Gradient Descent, Step-by-Step"'),
'59': ('SGD noisy per-row steps', 'N', ['Race: batch vs SGD on the same contours, SGD zig-zags one row per frame and highlights the row used | Plotly frames | sklearn diabetes | medium'], 'StatQuest "Stochastic Gradient Descent, clearly explained"'),
'60': ('mini-batch steps', 'N', ['Extend the 59 race to 3 runners (batch, mini-batch 32, SGD) with equal compute per frame | Plotly frames | sklearn diabetes | simple (reuses 59 script)'], ''),
'61': ('', '-', [], ''),
'62': ('bias-variance from refitting on new samples', 'N', ['Draw 20 training sets from the same true curve; refit degree 1 vs degree 15 each frame; ghost fits pile up (wide spread = variance, offset of mean fit = bias) | Plotly frames | Note synthetic sine data | medium'], 'StatQuest "Machine Learning Fundamentals: Bias and Variance"; R2D3 part 2'),
'63': ('lambda pulling slope toward 0', 'N', ['Sweep lambda: line flattens through 2 points while the penalty and SSE bars trade off | Plotly frames | the Note\'s two_points data | simple'], 'StatQuest "Ridge Regression, clearly explained"'),
'64': ('', '-', [], ''),
'65': ('ridge GD with shrink step', 'N', ['Ridge GD path on contours for 3 lambda values, endpoints move toward origin | Plotly frames | diabetes | simple'], ''),
'66': ('loss curve changing with lambda', 'Y', [], ''),
'67': ('lasso loss kink', 'Y', [], 'StatQuest "Lasso Regression, clearly explained"'),
'68': ('coefficients hitting exactly 0', 'N', ['Diamond vs circle constraint growing until it touches the loss ellipse; lasso touches a corner (coef=0) | Manim | 2-coef diabetes slice | medium', 'Coefficient paths vs lambda, lasso lines snapping to 0 | Plotly frames | diabetes | simple'], 'StatQuest "Ridge vs Lasso Regression, visualized"'),
'69': ('l1/l2 mix', 'N', ['Constraint shape morphing from diamond to circle as l1_ratio goes 1 -> 0 | Manim | none (geometry) | simple'], 'StatQuest "Elastic Net Regression"'),
'70': ('perceptron trick moving the line', 'N', ['Line swinging after each misclassified point pick (the abc update) | Manim | Note toy points | medium'], ''),
'71': ('perceptron training', 'Y', [], ''),
'72': ('', '-', [], ''),
'73': ('', '-', ['Animate log loss: one point dragged across the boundary, its -log(p) bar shooting up | Plotly frames | Note two_models data | simple'], 'StatQuest "Logistic Regression Details Pt 2: Maximum Likelihood"'),
'74': ('sigmoid slope along the curve', 'N', ['Tangent line riding the sigmoid with sigma(1-sigma) traced below | Manim | none | simple'], '3b1b Essence of Calculus Ch2 (derivative as slope)'),
'75': ('logistic GD boundary rotating', 'N', ['Decision boundary rotating over epochs with loss curve beside | Plotly frames | Note make_classification set | simple'], 'StatQuest "Logistic Regression" series'),
'76': ('', '-', ['Confusion-matrix cells filling one prediction at a time | Plotly frames | Note heart test set | simple'], 'StatQuest "The Confusion Matrix"'),
'77': ('threshold trading precision for recall', 'N', ['Threshold slider sweep: points flip colour, precision/recall bars move | Plotly frames | Note spam/heart scores | simple'], 'StatQuest "Sensitivity and Specificity"'),
'78': ('threshold sweep tracing ROC', 'Y', [], 'StatQuest "ROC and AUC, clearly explained"'),
'79': ('', '-', [], 'StatQuest "Neural Networks Pt 5: ArgMax and SoftMax"'),
'80': ('boundary bending with degree', 'N', ['Sweep polynomial degree 1->5; boundary on make_moons bends; train/test accuracy ticks | Plotly frames | make_moons | simple'], ''),
'81': ('C sweep', 'N', ['Sweep C: boundary and coefficient sizes change together | Plotly frames | breast cancer 2 features | simple'], ''),
'82': ('shrinking the sample space', 'N', ['Venn region zooms to B and re-normalises to fill the frame (P(A|B)) | Manim | Note dice example | simple'], '3b1b "Bayes theorem, the geometry of changing beliefs"'),
'83': ('', '-', ['Grid square: independent events as a perfect rectangle split, dependent as a skewed split | TikZ | Note example | simple'], ''),
'84': ('', '-', ['Two TikZ Venns side by side, disjoint vs overlapping, with the addition rule written in each | TikZ | Note example | simple'], ''),
'85': ('updating belief with evidence', 'N', ['3b1b-style population square: prior slice, evidence carves likelihood strips, posterior = remaining shaded share | Manim | Note spam numbers | medium'], '3b1b "Bayes theorem, the geometry of changing beliefs" and "The medical test paradox"'),
'86': ('', '-', [], '3b1b "The medical test paradox"'),
'87': ('', '-', ['Word-count bars multiplying into a class score, per class | Plotly | Note weather/tennis table | simple'], 'StatQuest "Naive Bayes, clearly explained"'),
'88': ('', '-', [], ''),
'89': ('', '-', ['Lookup-table heatmap of P(feature|class) from the fitted model | Plotly | weather data | simple'], ''),
'90': ('', '-', ['Two class Gaussians with a test point; likelihood heights shown as bars | Plotly | Note data | simple'], 'StatQuest "Gaussian Naive Bayes"'),
'91': ('KNN neighbourhood vote', 'N', ['Test point grows a circle until k neighbours caught; vote tally; then sweep k 1->50 with boundary smoothing | Plotly frames | breast cancer (2 features) | medium'], 'StatQuest "K-nearest neighbors"'),
'92': ('margin search', 'Y', [], 'StatQuest "Support Vector Machines Part 1: Main Ideas"'),
'93': ('', '-', [], ''),
'94': ('C trading margin for errors', 'N', ['Sweep C: margin width shrinks, slack sticks shorten | Plotly frames | Note toy data | simple'], ''),
'95': ('lifting into 3D', 'Y', [], 'StatQuest "Polynomial kernel" and "RBF kernel"'),
'96': ('', '-', ['Boundary for linear/poly/RBF kernels on make_circles, plus gamma sweep for RBF | Plotly frames | make_circles | simple'], ''),
'97': ('greedy split search', 'Y', [], 'StatQuest "Decision and Classification Trees"; R2D3 "A visual introduction to ML" part 1'),
'98': ('', '-', ['max_depth sweep: boundary goes blocky -> fragmented with train/test accuracy | Plotly frames | Note data | simple'], ''),
'99': ('SSE split sweep', 'Y', [], 'StatQuest "Regression Trees"'),
'100': ('', '-', [], ''),
'101': ('', '-', ['Wisdom-of-crowd demo: 1, 5, 25 weak models averaged, error falls | Plotly frames | make_classification | simple'], ''),
'102': ('', '-', [], ''),
'103': ('hard vs soft vote', 'N', ['Per-point vote tally animation for 3 classifiers, hard vs soft disagree on a border point | Plotly frames | iris 2 features | simple'], ''),
'104': ('', '-', ['Three regressors\' curves and their average fading in | Plotly | Note data | simple'], ''),
'105': ('bootstrap + average', 'Y', [], 'StatQuest "Bootstrapping main ideas"'),
'106': ('', '-', ['Decision surfaces of single tree vs bagging growing n_estimators 1->100 | Plotly frames | make_classification | simple'], ''),
'107': ('', '-', ['Bagged regression curve smoothing as trees are added | Plotly frames | Note data | simple'], ''),
'108': ('trees built on bootstrap + feature subsets, then voting', 'N', ['Forest grows tree by tree: each tree\'s rows and feature subset highlighted, then the vote map sharpens | Plotly frames | placement / make_classification | medium'], 'StatQuest "Random Forests Part 1"'),
'109': ('variance falling with trees', 'N', ['Boundary on make_circles for 1, 10, 100 trees | Plotly frames | make_circles | simple'], ''),
'110': ('column sampling', 'Y', [], ''),
'111': ('', '-', ['Hyperparameter sweep surfaces (max_features, max_samples) | Plotly frames | Note data | simple'], ''),
'112': ('', '-', ['Grid vs random search points dropping on the score surface | Plotly frames | heart | simple'], ''),
'113': ('OOB vote', 'Y', [], ''),
'114': ('', '-', [], ''),
'115': ('boosting stages', 'Y', [], 'StatQuest "AdaBoost, clearly explained"'),
'116': ('sample weights growing on mistakes', 'N', ['Points resize by weight each stage; stump line changes; alpha bar | Plotly frames | Note toy data | medium'], 'StatQuest "AdaBoost"'),
'117': ('', '-', [], ''),
'118': ('', '-', ['n_estimators/learning_rate sweep surface | Plotly frames | Note data | simple'], ''),
'119': ('parallel vs sequential', 'N', ['Side by side: bagging trees appear all at once, boosting trees one at a time each fixing residuals | Plotly frames | Note data | simple'], ''),
'120': ('fitting residuals stage by stage', 'Y', [], 'StatQuest "Gradient Boost Part 1"'),
'121': ('', '-', [], 'StatQuest "Gradient Boost Part 2: Regression Details"'),
'122': ('log-odds updated by trees', 'N', ['Probabilities per point climbing toward 0/1 stage by stage, with residual bars | Plotly frames | CGPA-placement | medium'], 'StatQuest "Gradient Boost Part 3/4: Classification"'),
'123': ('', '-', [], 'StatQuest "XGBoost Part 1"'),
'124': ('similarity-score split search', 'N', ['Threshold slides across sorted residuals, similarity/gain bars update, best split locks | Plotly frames | CGPA-package | medium'], 'StatQuest "XGBoost Part 1: Regression"'),
'125': ('', '-', ['Cover/similarity bars for classification splits | Plotly | Note data | simple'], 'StatQuest "XGBoost Part 2: Classification"'),
'126': ('', '-', [], 'StatQuest "XGBoost Part 3: Mathematical Details"'),
'127': ('', '-', [], ''),
'128': ('k-means assign/update loop', 'Y', [], 'StatQuest "K-means clustering"'),
'129': ('', '-', [], ''),
'130': ('', '-', [], ''),
'131': ('agglomerative merging', 'Y', [], 'StatQuest "Hierarchical Clustering"'),
'132': ('DBSCAN expansion', 'Y', [], 'StatQuest "Clustering with DBSCAN"'),
'133': ('SMOTE interpolation', 'Y', [], ''),
'134': ('Bayesian search', 'Y', [], ''),
'210': ('', '-', ['Roadmap as clickable TikZ map with one thumbnail of each Note\'s key figure | TikZ | none | simple'], ''),
'220': ('sample drawn from population', 'N', ['Dots sampled from a population one by one; sample mean marker wanders | Plotly frames | Titanic fares | simple'], ''),
'221': ('mean pulled by outlier', 'N', ['Drag one salary upward: mean marker slides, median stays | Plotly frames | Note salaries | simple'], ''),
'222': ('', '-', [], ''),
'223': ('', '-', [], ''),
'230': ('box plot built', 'Y', [], 'StatQuest "Quantiles and Percentiles"'),
'231': ('', '-', ['Correlation sweep: point cloud morphs from r=-1 to 1 with quadrant products coloured | Plotly frames | synthetic | simple'], 'StatQuest "Covariance" and "Pearson\'s Correlation"'),
'240': ('', '-', [], ''),
'241': ('CDF built from PMF', 'Y', [], ''),
'242': ('histogram -> density', 'Y', [], 'StatQuest "Histograms"'),
'243': ('KDE bumps summing; bandwidth', 'N', ['Kernels drop on each point and sum; then bandwidth sweep | Plotly frames | Note height data | simple'], ''),
'250': ('pdf built', 'Y', [], 'StatQuest "The Normal Distribution"; 3b1b "Why pi is in the normal distribution"'),
'251': ('standardising to z', 'N', ['Shift then squash a normal curve into N(0,1), area under z kept equal | Manim | Note heights | simple'], ''),
'252': ('', '-', ['Skew slider: distribution leans while mean/median/mode markers separate | Plotly frames | skew-normal | simple'], ''),
'253': ('', '-', [], ''),
'260': ('QQ plot built', 'Y', [], 'StatQuest "Quantile-Quantile Plots"'),
'261': ('', '-', [], ''),
'262': ('', '-', [], ''),
'270': ('Bernoulli trials adding up to binomial', 'N', ['Coin flips drop into count bins (Galton-board style), binomial PMF emerges | Plotly frames | Note likes example | simple'], '3b1b "Binomial distributions | Probabilities of probabilities"'),
'271': ('CLT pile-up', 'Y', ['Upgrade: 3 skewed populations (exponential, uniform, bimodal) piling up sample means side by side as n grows | Plotly frames | Note populations | medium'], '3b1b "But what is the Central Limit Theorem?"; StatQuest "The Central Limit Theorem"; Seeing Theory'),
'272': ('CLT estimating fare mean', 'N', ['Repeated samples of Titanic fares; each sample mean and its interval appear | Plotly frames | Titanic Fare | simple'], ''),
'280': ('', '-', [], 'StatQuest "Confidence Intervals, clearly explained"'),
'281': ('100 intervals, 95 catch the mean', 'N', ['Intervals drop one per frame; misses turn red; running coverage counter -> 95% | Plotly frames | Titanic Fare | simple'], 'Seeing Theory "Confidence interval"'),
'282': ('t tails fatten for small n', 'N', ['df sweep: t curve approaches normal | Plotly frames | none | simple'], ''),
'290': ('', '-', ['Courtroom-style TikZ flow H0 -> evidence -> decision | TikZ | none | simple'], 'StatQuest "Hypothesis Testing and The Null Hypothesis"'),
'291': ('test statistic landing in/out of rejection region', 'N', ['z statistic dropped from repeated samples; rejection regions shaded; alpha sweep | Plotly frames | Note data | simple'], ''),
'292': ('power vs effect size and n', 'N', ['Two overlapping H0/H1 curves; slide effect size and n; alpha, beta, power areas resize | Plotly frames | none | medium'], 'StatQuest "Statistical Power" and "Power Analysis"'),
'300': ('p-value as tail area', 'Y', [], 'StatQuest "p-values: what they are" and "How to calculate p-values"'),
'301': ('', '-', [], 'StatQuest "t-tests"'),
'302': ('', '-', [], ''),
'330': ('', '-', [], ''),
'331': ('relative frequency converging', 'N', ['Running proportion of heads converging to 0.5 for 3 seeds | Plotly frames | simulated coins | simple'], 'Seeing Theory "Chance events"'),
'332': ('', '-', ['Expected value as balance point of a PMF, variance as spread bars | Manim | Note dice | simple'], 'StatQuest "Expected values"'),
'340': ('', '-', [], ''),
'341': ('', '-', ['Contingency table whose row slice zooms out to a conditional distribution | Plotly frames | Titanic class x survived | simple'], ''),
'350': ('', '-', ['Thumbnail strip of the 3b1b-style animations in 490-530 so the roadmap is visual | TikZ | none | simple'], 'Essence of Linear Algebra playlist'),
'360': ('', '-', ['Iris flowers as arrows in 2D/3D feature space, rotating | Plotly | iris | simple'], '3b1b Essence LA Ch1 "Vectors"'),
'361': ('', '-', [], ''),
'362': ('', '-', [], '3b1b Essence LA Ch9'),
'363': ('', '-', ['Plane w.x+b=0 with normal vector; slide b to move the plane, rotate w to tilt it | Manim | iris 2 classes | medium'], ''),
'440': ('', '-', ['TikZ map: each maths branch -> the ML Notes that use it | TikZ | course_map | simple'], ''),
'490': ('span sweep', 'Y', [], '3b1b Essence LA Ch2'),
'500': ('grid transformed by matrix', 'Y', [], '3b1b Essence LA Ch3'),
'510': ('composition', 'Y', [], '3b1b Essence LA Ch4'),
'520': ('projection', 'Y', [], '3b1b Essence LA Ch9'),
'530': ('eigenvectors staying on their span', 'P', ['Manim: grid transforms, generic vectors knocked off their span, eigenvectors only stretch (highlighted); det_knob covers determinant, not the core eigen idea | Manim | the Note\'s matrix | medium'], '3b1b Essence LA Ch14 "Eigenvectors and eigenvalues"'),
'560': ('', '-', ['Binomial(n, lambda/n) morphing into Poisson as n grows | Plotly frames | Note counts | simple'], ''),
'570': ('', '-', [], ''),
'571': ('', '-', [], ''),
'572': ('', '-', [], 'StatQuest "Linear models Pt 2: t-tests and ANOVA"'),
'580': ('', '-', [], ''),
'590': ('two starts on non-convex loss', 'Y', [], ''),
'600': ('secant -> tangent', 'Y', [], '3b1b Essence of Calculus Ch2'),
'601': ('gradient as steepest uphill', 'N', ['Manim: surface with a point; rotate a direction arrow, directional slope peaks when aligned with grad | Manim | Note function | medium'], 'Khan Academy multivariable calculus (Grant Sanderson) "Gradient and graphs"'),
'602': ('Jacobian as local linear map', 'N', ['Manim: nonlinear map warping a grid; zoom on one point, warp looks linear = J | Manim | Note example | medium'], 'Khan Academy (Sanderson) "Local linearity / The Jacobian matrix"'),
'603': ('optimizer race', 'Y', [], 'Khan Academy (Sanderson) "The Hessian"; 3b1b Calculus Ch11 Taylor'),
'610': ('rotate-stretch-rotate', 'Y', [], ''),
'611': ('', '-', [], ''),
'612': ('rank-k image rebuilding', 'N', ['Image rebuilt k=1,2,4,...,50 one frame each with error bar | Plotly frames | Note image | simple'], ''),
'613': ('', '-', [], ''),
'620': ('contour tangency', 'Y', [], 'Khan Academy (Sanderson) "Lagrange multipliers"'),
'621': ('', '-', ['Chord test: chord sliding along convex vs non-convex curve, red when it dips below | Manim | none | simple'], ''),
'622': ('', '-', ['Objective line sweeping across the feasible polygon until last touch | Manim | Note LP | simple'], ''),
'630': ('likelihood as parameter slides', 'Y', [], 'StatQuest "Probability is not Likelihood"'),
'631': ('likelihood sweep', 'Y', [], 'StatQuest "Maximum Likelihood, clearly explained"'),
'632': ('', '-', [], 'StatQuest "MLE for normal/binomial/exponential"'),
'633': ('noise -> loss; overfit', 'Y', [], ''),
'640': ('sampling from a mixture', 'Y', [], ''),
'641': ('EM iterations', 'Y', [], ''),
'1001': ('', '-', ['Roadmap thumbnails of key DL animations | TikZ | none | simple'], ''),
'1002': ('', '-', ['Feature-learning panel: hand features vs learned layer features | TikZ | none | simple'], '3b1b NN Ch1'),
'1003': ('', '-', ['Architecture gallery icons (MLP, CNN, RNN, Transformer) per section | TikZ | none | simple'], ''),
'1004': ('weighted sum -> step -> class', 'N', ['Inputs flow into a perceptron; weighted sum bar fills; step fires; point coloured on the plane | Manim | placement CGPA/IQ | simple'], '3b1b NN Ch1'),
'1005': ('perceptron trick loop', 'N', ['Same as 70 but in DL notation; reuse 70 animation and link | Manim | Note toy data | simple (reuse)'], ''),
'1006': ('loss-driven training', 'Y', [], ''),
'1007': ('XOR not separable', 'N', ['Line tries every angle on XOR, never separates; then two lines (hidden layer) do | Manim | XOR | simple'], ''),
'1008': ('', '-', [], ''),
'1009': ('', '-', [], 'TensorFlow Playground (already referenced)'),
'1010': ('forward pass', 'Y', ['Add 2-3 stills (frames) inside the sections; currently the only visual is one GIF | Plotly frames grid | Note network | simple'], '3b1b NN Ch1'),
'1011': ('', '-', [], ''),
'1012': ('', '-', [], '3b1b NN Ch1'),
'1013': ('', '-', [], ''),
'1014': ('', '-', ['Loss sweep: drag one prediction away from target, MSE/MAE/Huber bars grow differently | Plotly frames | Note data | simple'], ''),
'1015': ('backprop', 'Y', [], '3b1b NN Ch3 "What is backpropagation really doing?"; StatQuest "Backpropagation main ideas"'),
'1016': ('chain rule passing gradients backward', 'N', ['Computation graph: values flow forward, then local derivatives multiply backward edge by edge, each weight gets its number | Manim | the Note\'s 2-2-1 placement network | hard'], '3b1b NN Ch4 "Backpropagation calculus"; 3b1b Calculus Ch4 chain rule'),
'1017': ('weights walking down loss', 'N', ['Loss surface over 2 weights of the Note network; ball descends while the network\'s output fits the data | Plotly frames | Note data | medium'], '3b1b NN Ch2'),
'1018': ('gradient shrinking layer by layer', 'N', ['Gradient bars per layer over epochs: sigmoid deep net bars fade to zero, ReLU stay alive | Plotly frames | make_moons | medium'], ''),
'1019': ('', '-', [], ''),
'1020': ('batch vs SGD vs mini-batch on a NN', 'N', ['Loss curves racing for 3 batch sizes, frame per epoch | Plotly frames | Note data | simple'], ''),
'1021': ('', '-', ['TikZ problem->fix map (vanishing, overfit, slow) linked to Notes | TikZ | none | simple'], ''),
'1022': ('early stop at val minimum', 'N', ['Train/val curves draw epoch by epoch; patience counter; boundary overfitting beside | Plotly frames | make_circles | simple'], ''),
'1023': ('', '-', ['Loss contours before/after scaling with GD path (elongated vs round) | Plotly frames | Note salary/age data | simple'], ''),
'1024': ('random neurons dropped each step', 'N', ['Network where different neurons grey out each frame; at test all on with scaled weights | Manim | Note net | simple'], ''),
'1025': ('', '-', [], ''),
'1026': ('', '-', [], ''),
'1027': ('', '-', [], ''),
'1028': ('', '-', [], ''),
'1029': ('activations collapsing with bad init', 'N', ['Activation histograms per layer for zero/small/large init, frame per layer | Plotly frames | Note net | medium'], ''),
'1030': ('', '-', [], ''),
'1031': ('batch norm re-centring activations', 'N', ['Histograms of a layer\'s pre-activations drifting over epochs without BN, steady with BN | Plotly frames | Note net | medium'], ''),
'1032': ('', '-', [], 'Distill "Why Momentum Really Works" (Goh, 2017)'),
'1033': ('EWMA smoothing', 'Y', [], ''),
'1034': ('momentum', 'Y', [], 'Distill "Why Momentum Really Works"'),
'1035': ('NAG lookahead', 'Y', [], ''),
'1036': ('adagrad', 'Y', [], ''),
'1037': ('rmsprop', 'Y', [], ''),
'1038': ('adam', 'Y', [], ''),
'1039': ('', '-', [], ''),
'1040': ('features built layer by layer', 'N', ['Digit passes through layers; edge maps -> parts -> class, frame per layer | Plotly frames | MNIST + Note CNN | medium'], ''),
'1041': ('', '-', [], ''),
'1042': ('kernel sliding', 'Y', [], '3b1b "But what is a convolution?"; CNN Explainer (Wang et al.)'),
'1043': ('padding/stride', 'Y', [], 'Dumoulin & Visin "A guide to convolution arithmetic" (GIFs)'),
'1044': ('max pool window', 'Y', [], ''),
'1045': ('', '-', ['Shape-flow strip: a digit\'s tensor shape at each LeNet layer (feature maps shown) | Plotly | MNIST | simple'], ''),
'1046': ('', '-', [], ''),
'1047': ('gradient flowing back through conv', 'N', ['Upstream gradient map convolved with flipped kernel back to input, cell by cell | Manim | Note 3x3 example | hard'], ''),
'1048': ('', '-', [], ''),
'1049': ('', '-', [], ''),
'1050': ('augmented copies', 'Y', [], ''),
'1051': ('', '-', ['Top-5 prediction bars per sample image from the pretrained net | Plotly | Note images | simple'], ''),
'1052': ('', '-', [], ''),
'1053': ('', '-', ['Frozen vs trainable layers drawn per strategy, with accuracy curves | TikZ + Plotly | cats vs dogs | simple'], ''),
'1054': ('', '-', [], ''),
'1055': ('', '-', [], ''),
'1056': ('RNN unrolling', 'Y', [], 'StatQuest "Recurrent Neural Networks (RNNs), clearly explained"'),
'1057': ('', '-', [], ''),
'1058': ('', '-', [], ''),
'1059': ('gradient through time', 'N', ['Unrolled RNN with gradient pulses travelling back through each timestep, fading with distance | Manim | IMDB-length toy sequence | medium'], ''),
'1060': ('', '-', [], ''),
'1061': ('', '-', [], 'Olah "Understanding LSTM Networks" (blog)'),
'1062': ('gates', 'Y', [], 'Olah "Understanding LSTM Networks"; StatQuest "LSTM, clearly explained"'),
'1063': ('', '-', ['Next-word prediction bars updating as each word is typed | Plotly frames | Note corpus | simple'], ''),
'1064': ('GRU gates', 'N', ['Reuse the 1062 gate animation style for reset/update gates on one sequence | Manim | Note example | medium'], ''),
'1065': ('', '-', ['Stacked unroll with info flowing up and right | Manim | none | simple'], ''),
'1066': ('two passes', 'N', ['Forward and backward passes sweep the sentence, states meet per word | Manim | Note POS example | simple'], ''),
'1067': ('', '-', [], ''),
'1068': ('greedy decoding', 'Y', [], 'StatQuest "Sequence-to-Sequence (seq2seq) Encoder-Decoder Neural Networks"'),
'1069': ('decoder attending to source words', 'N', ['For each output word, attention weights light up source words (moving heatmap row) and the context vector is built | Plotly frames | Note translation example | medium'], 'StatQuest "Attention for Neural Networks"; Alammar "Visualizing a NMT model"'),
'1070': ('', '-', [], ''),
'1071': ('', '-', [], '3b1b DL Ch5 "But what is a GPT?"; Alammar "The Illustrated Transformer"'),
'1072': ('', '-', [], '3b1b DL Ch6 "Attention in transformers"'),
'1073': ('QKV attention rows', 'Y', [], '3b1b DL Ch6; StatQuest "Transformer Neural Networks"'),
'1074': ('', '-', ['Softmax saturation as d grows: weights collapse to one-hot unless scaled | Plotly frames | Note dot_spread data | simple'], ''),
'1075': ('embeddings pulled by attention', 'Y', ['Add stills (frames grid) inside the sections; only one GIF now | Plotly | Note | simple'], '3b1b DL Ch6 (embedding vectors moved by attention)'),
'1076': ('', '-', [], ''),
'1077': ('heads in parallel', 'N', ['Same sentence through 2-4 heads, each head\'s weight map appears, then concat | Plotly frames | Note sentence | medium'], '3b1b DL Ch6 (multi-head)'),
'1078': ('PE waves', 'Y', [], ''),
'1079': ('', '-', ['Same activation matrix normalised along batch axis vs feature axis, highlighted direction | Manim | Note imdb_padding example | simple'], ''),
'1080': ('token flowing through encoder block', 'N', ['One token\'s vector through attention -> add&norm -> FFN -> add&norm, values shown | Manim | Note example | medium'], 'Alammar "The Illustrated Transformer"'),
'1081': ('mask fill', 'Y', [], ''),
'1082': ('decoder queries attending encoder keys', 'N', ['Decoder row queries sweep across encoder outputs, cross-attention heatmap fills row by row | Plotly frames | Note translation | simple'], ''),
'1083': ('decoder block flow', 'N', ['Masked self-attn -> cross-attn -> FFN for one target token | Manim | Note example | medium'], ''),
'1084': ('autoregressive decode', 'Y', [], '3b1b DL Ch5'),
'1085': ('end-to-end training + inference', 'N', ['One sentence pair through the full model: encoder, decoder steps, loss; stitched from 1073/1080/1084 frames | Plotly frames | Note example | hard'], '3b1b DL Ch5-7; Alammar "The Illustrated Transformer"'),
}

# Extra proposals for weak / text-heavy Notes whose process is already animated or that have no single process
EXTRA = {
'18': ['Annotated HTML tree -> DataFrame row: highlight the tag find_all hits and the cell it fills, one panel per step (sections 3-8) | TikZ | the Note\'s AmbitionBox company card | simple'],
'24': ['Scaling experiment (section 8): KNN/LR boundary before vs after scaling on the same axes, plus loss contours turning from ellipse to circle | Plotly | Note salary/age data | simple'],
'31': ['Yeo-Johnson (section 4): lambda sweep on a column with negatives, histogram + QQ beside it | Plotly frames | Note concrete-strength columns | simple'],
'32': ['Equal-frequency vs equal-width bins on Titanic Age as two coloured rug strips with bin counts (sections 3-6, 10) | Plotly | Titanic | simple'],
'40': ['Section 5 stills: the example table with filled cells highlighted per round (frames of mice_steps.gif reused) | Plotly frames grid | Note table | simple'],
'42': ['Train-only limits (section 11): limits learned on train, applied to test points; a test outlier shown capped | Plotly | placement CGPA | simple'],
'44': ['Percentile cut-off sweep (section 8): 1st/99th -> 5th/95th, points trimmed/capped live | Plotly frames | Note height/weight | simple'],
'71': ['Data + code walk: highlight the row used per update next to the line move (frame grid of perceptron_anim placed in sections 2-4) | Plotly frames grid | Note data | simple'],
'78': ['Section 3: TPR/FPR as two bars filling from the confusion matrix as the threshold moves; section 5: AUC area shading in | Plotly frames | Note scores | simple'],
'86': ['Probability tree whose branch widths are drawn to scale (posterior = shaded leaf share) | TikZ | Note numbers | simple'],
'88': ['Formula build as a stacked TikZ derivation strip: Bayes -> chain rule -> naive product, each step a coloured box | TikZ | Note tennis table | simple'],
'102': ['Ensemble accuracy vs number of independent voters (binomial majority curve) with correlation slider | Plotly frames | computed | simple'],
'110': ['Section 3: node-level vs tree-level feature sampling drawn on one tree side by side | TikZ | Note | simple'],
'113': ['Section 3: bootstrap matrix (rows x trees) with OOB cells lit, then per-row vote | Plotly | heart | simple'],
'114': ['MDI computed live: impurity drop bars accumulating per split as the tree is walked | Plotly frames | make_classification | medium'],
'117': ['Weight bars per row per stage (sections 3-8) as one Plotly frame sequence: weights, resample, next stump | Plotly frames | Note toy data | medium'],
'120': ['Residual bars shrinking stage by stage alongside the fitted curve (sections 4-9); learning-rate comparison (section 12) | Plotly frames | Note five students | medium'],
'121': ['Pseudo-residual = -gradient: loss parabola per point with the arrow toward the target, then leaf value as the mean | Plotly | Note data | simple'],
'123': ['Timeline strip + speed bars (section 4, 9) | TikZ + Plotly | Note timings | simple'],
'126': ['Second-order Taylor of the loss at the current prediction (parabola touching log loss), leaf weight = -G/(H+lambda) shown as the parabola minimum | Plotly frames | Note data | medium'],
'128': ['Section 4: the five steps as stills extracted from kmeans_2d.gif (frames grid) | Plotly frames grid | Note students | simple'],
'129': ['Cluster scatter for k=2..6 as frames with WCSS bar | Plotly frames | student data | simple'],
'130': ['Code-to-picture: each method (assign, move, stop) shown next to its frame | Plotly frames grid | Note | simple'],
'131': ['Proximity matrix shrinking as clusters merge, next to the growing dendrogram (section 7) | Plotly frames | Note points | medium'],
'132': ['eps/MinPts sweep (section 13): clusters/noise recolour live | Plotly frames | Note moons | simple'],
'134': ['Workflow TikZ (study, trial, objective) for section 4-5 | TikZ | none | simple'],
'222': ['Deviation sticks from the mean for two classes with equal means but different spread; MAD and SD bars | Plotly | Note salaries | simple'],
'241': ['Two-dice sum PMF built by tossing (histogram converging to the triangle) | Plotly frames | simulated | simple'],
'242': ['Area-under-curve shading slides with b in P(a<X<b) while CDF height rises (section 8) | Plotly frames | Note | simple'],
'250': ['mu/sigma sweep (section 3) and 68-95-99.7 areas (section 6) | Plotly frames | Note heights | simple'],
'280': ['Interval width as n and confidence level change (section 7-8) | Plotly frames | Titanic | simple'],
'301': ['t-statistic built: sample mean distance over SE, dropped onto the t curve | Plotly frames | Titanic Age | simple'],
'302': ['Paired vs independent: the same data with and without pairing lines; SE bar shrinks when paired | Plotly | Note data | simple'],
'490': ['Linear dependence (section 7): third vector inside the plane of the first two, span does not grow | Manim | none | simple'],
'500': ['Section 3: non-linear vs linear warps of the grid (lines stay straight, origin fixed) | Manim | none | simple'],
'510': ['Section 4: product column-by-column: where i-hat lands after B, then after A | Manim | the Note\'s matrices | simple'],
'520': ['Section 6: 2D vector squashing the plane onto a number line (duality) | Manim | none | medium'],
'570': ['Test chooser as a TikZ decision tree with each leaf showing the Note\'s example plot thumbnail | TikZ | Note datasets | simple'],
'572': ['Between vs within variance: groups slide apart, F bar grows | Plotly frames | Titanic age by class | simple'],
'580': [],
'600': ['Rules (section 5) as geometric pictures: area of x^2 square growing (power rule), as in 3b1b | Manim | none | medium'],
'610': ['Stills from rotate_stretch_rotate into sections 3-5 | Manim frames grid | Note matrix | simple'],
'611': ['A^T A eigenvectors found by Manim: circle -> ellipse, axes highlighted, then sigma = sqrt(lambda) | Manim | the Note\'s 2x2 | medium'],
'613': ['PCA via SVD: data cloud, right singular vectors as axes, projection | Plotly | MNIST subset | simple'],
'620': ['Section 4: grad f and grad g arrows parallel at the tangent point (lambda = length ratio) | Manim | Note example | simple'],
'631': ['Section 3: product of likelihood bars for each point shrinking/growing as mu slides | Plotly frames | Note data | simple'],
'632': ['Normal MLE: (mu, sigma) surface with peak at sample mean/variance | Plotly | Note | simple'],
'633': ['Bernoulli target -> log loss: predicted p slides, likelihood bar and -log bar move together | Plotly frames | Note | simple'],
'641': ['Section 3: E-step colouring/M-step moving as stills from em_2d frames | Plotly frames grid | Old Faithful | simple'],
'1006': ['Section 4-5: loss as a function of the line (b sweep), surface of perceptron loss | Plotly frames | Note | simple'],
'1008': ['Network diagram with each weight labelled by its index, highlighted as named in section 5 | TikZ | Note net | simple'],
'1012': ['Argmax prediction bars for sample digits (section 6, 9) | Plotly | MNIST | simple'],
'1015': ['Section 7: one update with real numbers drawn on the network: forward values, error, then updated weights coloured by change | Manim | Note 2-2-1 placement net | medium'],
'1025': ['Dropout rate sweep: boundary and loss curves for p = 0, 0.2, 0.5 | Plotly frames | Note data | simple'],
'1026': ['Weight decay: weight histogram shrinking toward 0 over epochs as lambda grows | Plotly frames | make_moons | simple'],
'1032': ['Optimizer family tree linking to the race GIFs in 1034-1038 | TikZ | none | simple'],
'1034': ['Section 6: velocity vector + gradient vector added head-to-tail each step | Manim | Note valley | simple'],
'1035': ['Section 5: lookahead point drawn before the gradient is taken | Manim | Note valley | simple'],
'1036': ['Section 5: per-parameter accumulator bars growing, effective step shrinking | Plotly frames | Note sparse bowl | simple'],
'1037': ['Section 3: accumulator AdaGrad vs RMSProp over steps (grows vs levels off) | Plotly frames | Note | simple'],
'1038': ['Section 4: m and v traces with bias correction toggled | Plotly frames | Note | simple'],
'1039': ['Trials scatter (hp vs val score) filling in trial by trial | Plotly frames | Note diabetes trials | simple'],
'1044': ['Section 5: pooling applied per channel of a volume, shape shown | Manim | Note | simple'],
'1046': ['Parameter-count bars ANN vs CNN with the layer that dominates highlighted | Plotly | MNIST models | simple'],
'1048': ['Backward through flatten/ReLU/conv as a shape-and-mask strip | Manim | Note MNIST net | medium'],
'1049': ['Batch loading as a flowing image grid (section 4) | Plotly | cats vs dogs | simple'],
'1055': ['Section 6: one RNN cell reading words one by one, hidden state colour changing | Manim | IMDB sentence | simple'],
'1056': ['Section 5: hidden-state vector values per timestep as a heatmap growing column by column | Plotly frames | Note | simple'],
'1061': ['Two-path diagram: short-term path fading, cell-state highway keeping info (section 5-6) | Manim | Note story example | medium'],
'1062': ['Section 8: one time step with numbers, gate values as bars | Plotly frames | Note | simple'],
'1067': ['Timeline TikZ with architecture icons per stage | TikZ | none | simple'],
'1068': ['Encoder compressing a sentence into one context vector, bottleneck shown (section 3-4) | Manim | Note example | simple'],
'1070': ['Bahdanau vs Luong: where the score is computed (before vs after decoder step), side by side flow | Manim | Note | medium'],
'1071': ['Sequential RNN vs parallel transformer processing a sentence (timing race) | Manim | Note | simple'],
'1073': ['Section 7: Q, K, V projections drawn as arrows from one embedding | Manim | Note | medium'],
'1076': ['Same three equations side by side, encoder-decoder vs self, highlighted substitution | TikZ | Note | simple'],
'1081': ['Section 4: training (all at once, masked) vs inference (step by step) | Plotly frames | Note | simple'],
'1084': ['Frames grid of decode_anim placed in sections 3-7 | Plotly frames grid | Note | simple'],
}
