"""Builds docs/visual-audit.md from metrics.json (measure.py) and annotations.py (hand judgements)."""
import json, re, pathlib
from collections import Counter
from annotations import A, EXTRA

ROOT = pathlib.Path('/home/anshu/campusx')
IMG = re.compile(r'!\[.*?\]\(([^)\s]+\.(?:png|gif|svg|jpe?g|webp))\)')
SKIP = re.compile(r'summary|prerequisites|sources|key terms|references|further reading', re.I)
ORDER = ['strong', 'adequate', 'weak', 'text-heavy']
rows = json.load(open(ROOT / 'docs/visual-audit/metrics.json'))
key = lambda n: 'map' if n == '01-course-map' else n.split('-')[0]

def bare_sections(note):
    t = re.sub(r'<!-- where-this-fits.*?<!-- /where-this-fits -->', '', (ROOT / note / 'note.md').read_text(), flags=re.S)
    out = []
    for p in re.split(r'^## ', t, flags=re.M)[1:]:
        h = p.split('\n', 1)[0].strip()
        if re.match(r'\d+\.', h) and not SKIP.search(h) and not IMG.search(p):
            out.append(h.split('.')[0])
    return out

def score(x, a):
    cov = x['secfig'] / max(1, x['nsec']); w = x['wpv']
    s = 'text-heavy' if (w > 900 or cov < 0.3) else 'weak' if (w > 600 or cov < 0.5) else 'strong' if (w <= 400 and cov >= 0.6) else 'adequate'
    cap = {'N': 'weak', 'P': 'adequate'}.get(a)
    if cap and ORDER.index(s) < ORDER.index(cap):
        s = cap
    return s

def reason(x, p, a, s):
    bits = [f"{x['secfig']}/{x['nsec']} sections illustrated", f"{x['wpv']} words per visual"]
    if a == 'Y': bits.append('core process animated')
    elif a == 'N': bits.append('core process NOT animated')
    elif a == 'P': bits.append('GIF misses the core process')
    if x['figs'] + x['gifs'] <= 1: bits.append('only one visual')
    return '; '.join(bits)

for x in rows:
    p, a, v, g = A[key(x['note'])]
    x.update(p=p, a=a, v=v + EXTRA.get(key(x['note']), []), g=g)
    x['s'] = score(x, a)
    x['r'] = reason(x, p, a, x['s'])

c = Counter(x['s'] for x in rows)
proc = [x for x in rows if x['a'] != '-']
pc = Counter(x['a'] for x in proc)
L = []
w = L.append
w('# Visual audit of all Notes\n')
w('Generated by `docs/visual-audit/build.py` from `measure.py` (counts) and `annotations.py` (hand judgements). Re-run both after figure work.\n')
w('## 1. Summary\n')
w(f'- **Notes audited:** {len(rows)}')
w(f"- **Scores:** strong {c['strong']}, adequate {c['adequate']}, weak {c['weak']}, text-heavy {c['text-heavy']}")
w(f"- **Process ideas:** {len(proc)} Notes have a core process. Animated: {pc['Y']}. Animation misses the core: {pc['P']}. Not animated: {pc['N']}.")
w(f"- **Visuals in total:** {sum(x['figs'] for x in rows)} static figures, {sum(x['gifs'] for x in rows)} GIFs. {sum(1 for x in rows if x['gifs'])} Notes have at least one GIF.")
w(f"- **Median words per visual:** {sorted(x['wpv'] for x in rows)[len(rows)//2]}.")
w('- **Biggest gaps:** the DL theory block (1015-1018, 1059, 1064-1085) and the ensemble/boosting maths (102-126) are long text with one or two figures; their core processes (backprop, BPTT, attention, boosting stages) are mostly not animated.\n')
w('### Scoring rule\n')
w('- Counted per Note: image links in `note.md` (where-this-fits map excluded), GIFs, numbered `##` sections (Summary, Prerequisites, Sources, Key terms excluded) and prose words outside code and display maths.')
w('- **strong:** <=400 words per visual and >=60% of sections illustrated. **adequate:** <=600 words per visual and >=50% illustrated. **weak:** worse than adequate. **text-heavy:** >900 words per visual or <30% illustrated.')
w('- A Note whose core idea is a process with no animation is capped at **weak**; one whose GIF misses the core process is capped at **adequate**.')
w('- Process / animated / proposals are hand judgements from each Note\'s key points, section titles and figure names.\n')

TOP = [
 ('62', 'Bias-variance: 20 resampled training sets, degree-1 vs degree-15 fits pile up as ghosts', 'Plotly frames', 'medium'),
 ('1016', 'Backprop chain rule: forward values, then local derivatives multiplied backward edge by edge on the 2-2-1 placement net', 'Manim', 'hard'),
 ('58-60', 'Batch vs mini-batch vs SGD racing on the same diabetes loss contours (one script, three Notes)', 'Plotly frames', 'medium'),
 ('530', 'Eigenvectors: grid transforms, most vectors leave their span, eigenvectors only stretch', 'Manim', 'medium'),
 ('1069', 'Attention: each output word lights up the source words it reads; context vector built', 'Plotly frames', 'medium'),
 ('51', 'Least squares: residual squares on the line (left) linked to the dot on the (m,b) loss surface (right)', 'Plotly frames', 'medium'),
 ('85', 'Bayes as geometry: population square, evidence carves strips, posterior is the shaded share', 'Manim', 'medium'),
 ('68', 'Lasso vs ridge: diamond vs circle growing until it touches the loss ellipse; lasso hits a corner', 'Manim', 'medium'),
 ('91', 'KNN: circle grows to k neighbours, vote tally, then k sweep smooths the boundary', 'Plotly frames', 'medium'),
 ('281', 'Confidence intervals: 100 intervals drop, misses turn red, coverage counter settles at 95%', 'Plotly frames', 'simple'),
 ('108', 'Random forest: trees added one by one (rows + feature subset highlighted), vote map sharpens', 'Plotly frames', 'medium'),
 ('122', 'Gradient boosting classification: per-point probabilities climb stage by stage with residual bars', 'Plotly frames', 'medium'),
 ('116', 'AdaBoost: points resize by weight each stage, new stump, alpha bar', 'Plotly frames', 'medium'),
 ('124', 'XGBoost split search: threshold slides, similarity and gain bars update, best split locks', 'Plotly frames', 'medium'),
 ('1018', 'Vanishing gradients: per-layer gradient bars fade over epochs for sigmoid, stay alive for ReLU', 'Plotly frames', 'medium'),
 ('601', 'Gradient: rotate a direction arrow on a surface; slope peaks when aligned with the gradient', 'Manim', 'medium'),
 ('1017', 'Loss surface over two weights: ball descends while the network output fits the data', 'Plotly frames', 'medium'),
 ('270', 'Binomial from Bernoulli: Galton-board flips drop into bins, PMF emerges', 'Plotly frames', 'simple'),
 ('243', 'KDE: a kernel drops on each point and sums; bandwidth sweep', 'Plotly frames', 'simple'),
 ('292', 'Power: H0/H1 curves; effect size and n sliders resize alpha, beta, power areas', 'Plotly frames', 'medium'),
 ('1059', 'BPTT: gradient pulses travel back through the unrolled RNN and fade with distance', 'Manim', 'medium'),
 ('1077', 'Multi-head attention: the same sentence through 2-4 heads, each weight map, then concat', 'Plotly frames', 'medium'),
 ('1080', 'Encoder block: one token vector through attention, add&norm, FFN, add&norm', 'Manim', 'medium'),
 ('54', 'Normal equation: y projected onto the column space of X, residual perpendicular', 'Manim', 'medium'),
 ('70 + 1005', 'Perceptron trick: line swings after each misclassified point (one animation, two Notes)', 'Manim', 'medium'),
 ('75', 'Logistic regression GD: boundary rotates over epochs, loss curve beside', 'Plotly frames', 'simple'),
 ('77', 'Precision/recall threshold sweep: points flip colour, P and R bars move', 'Plotly frames', 'simple'),
 ('612', 'Low-rank approximation: image rebuilt k=1..50, error bar falls', 'Plotly frames', 'simple'),
 ('1024', 'Dropout: different neurons grey out each step; all on at test with scaled weights', 'Manim', 'simple'),
 ('1040', 'CNN hierarchy: a digit through each layer, edges -> parts -> class', 'Plotly frames', 'medium'),
]
w('### Top 30 visual upgrades (teaching value per effort)\n')
w('Ranked by: core process a learner cannot picture from text, used by many later Notes, and effort. Every item is currently not animated or only shown as stills.\n')
w('| # | Note | What to animate | Tool | Effort |')
w('|---|---|---|---|---|')
for i, (n, what, tool, eff) in enumerate(TOP, 1):
    w(f'| {i} | {n} | {what} | {tool} | {eff} |')
w('')
w('### Batching plan\n')
w('Each agent owns one toolchain and one topic block, so scripts and styles are reused inside the batch. Run A, B, C and E first (they hold most of the top 30), then D, F, G; H fills free slots.\n')
w('| Agent | Tool | Notes | Top-30 items |')
w('|---|---|---|---|')
for row in [
 ('A: regression + GD', 'Plotly frames', '51, 52, 53, 58, 59, 60, 62, 63, 65, 75, 1017, 1020, 1023', '1, 3, 6, 17, 26'),
 ('B: linear algebra + calculus', 'Manim', '530, 54, 68 (geometry), 69, 74, 363, 490, 500, 510, 520, 600, 601, 602, 611, 620, 621, 622', '4, 8, 16, 24'),
 ('C: classification + ensembles', 'Plotly frames', '77, 80, 81, 91, 94, 96, 98, 101, 103, 106-109, 116, 117, 119, 120, 122, 124, 126, 68 (coef paths)', '9, 11-14, 27'),
 ('D: statistics + probability', 'Plotly frames; Manim for 82/85/251/332', '82, 85, 220, 221, 243, 251, 252, 270, 272, 281, 282, 291, 292, 331, 560, 612', '7, 10, 18-20, 28'),
 ('E: DL core maths', 'Manim', '1004, 1007, 70 + 1005, 1015, 1016, 1024, 1047, 1048, 1059', '2, 21, 25, 29'),
 ('F: DL training dynamics', 'Plotly frames', '1018, 1022, 1025, 1026, 1029, 1031, 1040, 1034-1038 (stills)', '15, 30'),
 ('G: sequences + attention', 'Plotly frames + Manim', '1055, 1056, 1061, 1064, 1066, 1068-1071, 1073, 1077, 1080-1085', '5, 22, 23'),
 ('H: TikZ quick wins', 'TikZ', '12, 14, 23, 26, 33, 34, 41, 83, 84, 86, 88, 210, 290, 350, 440, 570, 1001-1003, 1008, 1021, 1032, 1067, 1076', '-'),
]:
    w('| ' + ' | '.join(row) + ' |')
w('')
w('Shared rules for every agent: one strong animation per core idea before any small static plot; GIF + `_frames.png` grid for the PDF (pattern: `603-hessian-and-multivariate-taylor/images/optimizer_race.py`); Manim Community 0.20 in the `campusx` env; no matplotlib; data from the Note itself; credit the gold source in the caption or Sources, never copy frames.\n')

w('## 2. Gold-standard visual sources by topic\n')
w('We recreate the idea with our own data and credit the source. Notes listed are the ones each source would strengthen most.\n')
w('| Source | Strengthens Notes |')
w('|---|---|')
gold = [
 ('3Blue1Brown, Essence of Linear Algebra Ch1 Vectors', '360, 361'),
 ('3b1b ELA Ch2 Linear combinations, span, basis', '490'),
 ('3b1b ELA Ch3 Linear transformations and matrices', '500, 48'),
 ('3b1b ELA Ch4 Matrix multiplication as composition', '510'),
 ('3b1b ELA Ch8 Nonsquare matrices; Ch9 Dot products and duality', '520, 362, 54'),
 ('3b1b ELA Ch13 Change of basis', '47, 48'),
 ('3b1b ELA Ch14 Eigenvectors and eigenvalues', '530, 48, 611'),
 ('3b1b Essence of Calculus Ch2 Paradox of the derivative', '600, 74'),
 ('3b1b Calculus Ch3-4 Derivative formulas through geometry; chain rule visualized', '600, 1016'),
 ('3b1b Calculus Ch11 Taylor series', '603, 126'),
 ('Grant Sanderson, Khan Academy multivariable calculus (gradient, Jacobian, Hessian, Lagrange multipliers)', '601, 602, 603, 620'),
 ('3b1b Neural Networks Ch1 "But what is a neural network?"', '1002, 1004, 1009, 1010, 1012'),
 ('3b1b NN Ch2 "Gradient descent, how neural networks learn"', '57, 58, 1017, 1020'),
 ('3b1b NN Ch3 "What is backpropagation really doing?"', '1015, 1016'),
 ('3b1b NN Ch4 "Backpropagation calculus"', '1016, 1017, 1018'),
 ('3b1b DL Ch5 "But what is a GPT?"', '1071, 1084, 1085'),
 ('3b1b DL Ch6 "Attention in transformers, step-by-step"', '1072, 1073, 1074, 1075, 1077, 1081'),
 ('3b1b DL Ch7 "How might LLMs store facts" (MLP blocks)', '1080, 1085'),
 ('3b1b "Bayes theorem, the geometry of changing beliefs"; "The medical test paradox"', '82, 85, 86'),
 ('3b1b "Binomial distributions | Probabilities of probabilities"', '270, 632'),
 ('3b1b "But what is the Central Limit Theorem?"', '271, 272'),
 ('3b1b "Why pi is in the normal distribution"; "Gaussian + Gaussian = Gaussian"', '250, 271'),
 ('3b1b "But what is a convolution?"', '1042, 1047'),
 ('StatQuest: Linear Regression; R-squared; Gradient Descent Step-by-Step; Stochastic Gradient Descent', '50, 51, 52, 57, 58, 59'),
 ('StatQuest: Bias and Variance; Ridge; Lasso; Ridge vs Lasso visualized; Elastic Net', '62, 63, 67, 68, 69'),
 ('StatQuest: Logistic Regression series; Odds and log-odds', '72, 73, 75, 122'),
 ('StatQuest: Confusion Matrix; Sensitivity and Specificity; ROC and AUC', '76, 77, 78'),
 ('StatQuest: Naive Bayes; Gaussian Naive Bayes', '87, 90'),
 ('StatQuest: K-nearest neighbors; SVM Main Ideas; Polynomial and RBF kernels', '91, 92, 95'),
 ('StatQuest: Decision and Classification Trees; Regression Trees', '97, 99'),
 ('StatQuest: Bootstrapping; Random Forests Part 1-2', '105, 108, 113'),
 ('StatQuest: AdaBoost; Gradient Boost Part 1-4; XGBoost Part 1-4', '115, 116, 120-126'),
 ('StatQuest: K-means; Hierarchical Clustering; DBSCAN; PCA Main Ideas / Step-by-Step', '128, 131, 132, 47, 48'),
 ('StatQuest: Histograms; Normal distribution; Quantiles; QQ plots; Covariance; Pearson correlation', '242, 250, 230, 260, 231'),
 ('StatQuest: Central Limit Theorem; Confidence Intervals; p-values; Hypothesis testing; Statistical Power; t-tests and ANOVA', '271, 280, 300, 290, 292, 301, 572'),
 ('StatQuest: Probability is not Likelihood; Maximum Likelihood (normal, binomial, exponential)', '630, 631, 632'),
 ('StatQuest: Neural Networks Pt1-2 (backprop main ideas); ArgMax and SoftMax; RNN; LSTM; Seq2Seq; Attention; Transformers', '1009, 1015, 79, 1056, 1062, 1068, 1069, 1073'),
 ('Distill, "Why Momentum Really Works" (Goh, 2017)', '1032, 1034, 1035'),
 ('Chris Olah, "Understanding LSTM Networks"', '1061, 1062, 1064'),
 ('Jay Alammar, "The Illustrated Transformer"; "Visualizing a NMT model"', '1069, 1071, 1080, 1083'),
 ('Dumoulin and Visin, "A guide to convolution arithmetic" (animations)', '1043, 1044'),
 ('CNN Explainer (Wang et al., Georgia Tech)', '1042, 1052'),
 ('Seeing Theory (Brown University)', '271, 281, 331'),
 ('R2D3, "A visual introduction to machine learning" Parts 1-2', '97, 62'),
]
for s, n in gold:
    w(f'| {s} | {n} |')
w('')

w('## 3. Every Note\n')
w('Columns: static figures, GIFs, numbered sections with a figure, prose words per visual, core process and whether it is animated (Y / N / P = GIF misses the core / - = no process).\n')
w('| Note | Fig | GIF | Sections | Words/visual | Process | Anim | Score | Reason |')
w('|---|---|---|---|---|---|---|---|---|')
for x in rows:
    w(f"| [{x['note']}](../{x['note']}/note.md) | {x['figs']} | {x['gifs']} | {x['secfig']}/{x['nsec']} | {x['wpv']} | {x['p'] or '-'} | {x['a']} | {x['s']} | {x['r']} |")
w('')

w('## 4. Proposals per Note\n')
w('Every weak and text-heavy Note, and every Note with a process idea that is not animated. Format: what is shown | tool | data | effort. "Bare sections" are numbered sections with no figure.\n')
for x in rows:
    need = x['s'] in ('weak', 'text-heavy') or x['a'] in ('N', 'P') or x['v']
    if not need:
        continue
    w(f"### {x['note']} ({x['s']})\n")
    if x['p']:
        w(f"- **Process:** {x['p']} (animated: {x['a']})")
    bs = bare_sections(x['note'])
    if bs:
        w(f"- **Bare sections:** {', '.join(bs)}")
    for v in x['v']:
        w(f'- **Proposal:** {v}')
    if not x['v']:
        w('- **Proposal:** none needed beyond stills; add one figure per bare section from the Note\'s existing scripts.')
    if x['g']:
        w(f"- **Gold source:** {x['g']}")
    w('')
(ROOT / 'docs/visual-audit.md').write_text('\n'.join(L))
print(c, pc, len(L))
